remoteit/desktop

frontend/src/models/auth.ts

User will need to upgrade the desktop app when cognito is rolled out. API v27 will not support cognito login with Google and will not support 2-FA.
The plan is to have a new version of the desktop available before enabling cognito which will use API v28 and handle all of the cases for cognito sign in.

DESK-304. Update signin to handle cognito API failures and message user

---

backend/package-lock.json
backend/package.json
backend/src/Application.ts
backend/src/Controller.ts
backend/src/Server.ts
backend/src/environment.ts
frontend/package-lock.json
frontend/package.json
package-lock.json
package.json
src/AutoUpdater.ts
src/ElectronApp.ts
src/index.ts

Electron wasn't attached bi-directionally so the quit and restart commands didn't work.

DESK-358 autoupdate restart

---

backend/src/cliInterface.ts
frontend/src/pages/SetupPage/SetupPage.tsx

Provide a way for the Desktop to pickup changes made by the cli in the UI.
Load Desktop.
Observe Hosted page state.
On the command line make a change to the hosted system setup.
ie `sudo remoteit setup`
In desktop navigate away and back to the Hosted page.
You should see the state updated based on the cli change.
https://remoteit.atlassian.net/browse/DESK-278

[DESK-278] On load setup page also load the cli config values

---

backend/src/index.ts
src/AutoUpdater.ts

Prompt and stop system service before auto update restart. So that the old service can be killed before starting the new one on update. Especially because on windows the bin directory is removed.
This must be tested when 2.5.22-alpha can be updated to another version. Or ask @JamieRuderman for a test build with this code tagged as an older version.
<https://remoteit.atlassian.net/browse/DESK-389>

[DESK-389] Stop system service on auto-update enter restart

---

package.json

I would also like to stop supporting the AppImage Linux build. They take extra time to build and a long time to upload to GitHub. As well they incur additional testing effort and time and they haven't been downloaded almost at all. The couple times I could chalk up to my own testing, so we haven’t really started supporting them. https://somsubhra.com/github-release-stats/?username=remoteit&repository=desktop
1. Build desktop
2. No appimage assets are created
<https://remoteit.atlassian.net/browse/DESK-408>

[DESK-408] deprecate appImage support

---

frontend/src/components/Header/Header.tsx
frontend/src/components/UninstallSetting/UninstallSetting.tsx

Guest user should not be able to uninstall remoteit
1. Sign in to a registered device as a different user
2. Go to settings page
3. Uninstall should not be there.
4. Sign in as registered user and the uninstall command should be there.
<https://remoteit.atlassian.net/browse/DESK-414>

[DESK-414] Guest user should not be able to uninstall remoteit

---

backend/src/Application.ts
backend/src/CLI.ts
backend/src/Controller.ts
backend/src/User.ts
backend/src/index.ts
common/types.d.ts
frontend/src/models/auth.ts
src/TrayMenu.ts

Uninstall does not consistently log out the user.  When reopening the app the user is still signed in.  Upon investigation it appears that the front end was being killed before it could sign out.  Added Synchronization during uninstall for signout of frontend
- [n/a] I have added/updated tests for any code changes
- [n/a] Translation strings added/updated for all user-visible text
1. Sign in
2. Install Command Line Tools
3. Got to Settings
4. Uninstall Command Line Tools
5. You should be signed out and app close
6. Relaunch the app
7. You should be signed out
https://remoteit.atlassian.net/browse/DESK-497

[DESK-497] Add Synchronization during uninstall for signout of frontend

---

frontend/src/components/Setup/Setup.tsx
frontend/src/models/devices.ts
frontend/src/pages/DevicesPage/DevicesPage.tsx

Device list refresh should be without cache and also after target device change
1. Sign in
2. Setup a new device
3. It should appear right away on the device list
<https://remoteit.atlassian.net/browse/DESK-482>

[DESK-482] device list refresh should be without cache and also after target device change

---

backend/src/Application.ts
backend/src/CLI.ts
backend/src/constants.ts
backend/src/environment.ts

To track the difference between headless and standard desktop
1. setup and add a service to a device
2. Look into the logs at the commands for the manufacturer-id option and data
<https://remoteit.atlassian.net/browse/DESK-490>

[DESK-490] setting manufacture-id on add and setup commands

---

backend/src/environment.ts

Fix manufacture id - was always showing as headleass because of a race condition.
When registering you can see in the log file the manufacture-id set to validate when adding a device or service.
<https://remoteit.atlassian.net/browse/DESK-499>

[DESK-499] Fix manufacture id

---

frontend/src/pages/SetupServices/SetupServices.tsx
frontend/src/pages/SetupWaiting/SetupWaiting.tsx

Upon registration the device list was not being re-loaded to update the device state.
1. Sign in
2. Register your system
3. After complete visit the device list
4. You should your system in the list
<https://remoteit.atlassian.net/browse/DESK-506>

[DESK-506] Refresh device list upon registration

---

frontend/src/pages/SetupDevice/SetupDevice.tsx
frontend/src/pages/SetupWaiting/SetupWaiting.tsx
readme.md

Set loading state on setup page to account for device list loading and set device name on completion
1. Start Desktop on a system 1 that is not registered
2. Note the hostname in the setup page
3. Go to another system or VM and register that device with the hostname of system 1
2. Go to a browser and open http://localhost:29999 on system 1
3. Login and watch the system name in the setup field start with the hostname and then change to the hostname-1 after loading completes.
<https://remoteit.atlassian.net/browse/DESK-534>

[DESK-534] Set loading state on setup page to account for device list loading and set device name on completion

---

frontend/src/helpers/lanSharing.ts

Fixing private ip address reference in lan sharing
1. Sign in
2. Go to a device -> service -> service details -> lan sharing
3. Click enable lan sharing
4. Select single ip restriction
5. Save
Should have no errors.
<https://remoteit.atlassian.net/browse/DESK-540>

[DESK-540] Fixing private ip address reference in lan sharing

---

frontend/src/models/auth.ts

move identify to setUser so that it consistently gets called
Sign in with new version of deskto
Verify segment events and page views are tagged with userid
Long term we need to check that userid is set in all track events in segment data for new versions
https://remoteit.atlassian.net/browse/DESK-548

[DESK-548] move identify to setUser

---

backend/src/CLI.ts
backend/src/Installer.test.ts
backend/src/Installer.ts
backend/src/binaryInstaller.ts
backend/src/preferences.ts
frontend/src/components/InstallationNotice/InstallationNotice.tsx

Desktop should track it's version and run cli restart services on any update incase they get killed.
1. Startup Desktop
2. Quit Desktop
3. Find the preferences file (see readme.md)
4. Change the indicated version to an older version in the preferences file
5. Stop the services `sudo remoteit service stop`
6. Restart Desktop
7. You should see an indication that systems services need to be installed/updated
8. Device should come back online
<https://remoteit.atlassian.net/browse/DESK-547>

[DESK-547] Detect desktop only updates and start CLI system services

---

frontend/src/buttons/DeleteButton/DeleteButton.tsx
frontend/src/buttons/DeleteButton/index.ts
frontend/src/components/ServiceList/ServiceList.tsx
frontend/src/models/devices.ts
frontend/src/pages/ServicesPage/ServicesPage.tsx

**Adds a delete icon/action to a device that I own.**
If I create a device in Desktop and don't have any services it doesn't show in portal and I can't delete it.  I should be able to delete a device in Desktop so I can clean up.
1. Sign in
2. Go to an offline device you own
3. Click it in the device list
4. You should see it delete after a few moments
<https://remoteit.atlassian.net/browse/DESK-509>

[DESK-509] Add delete device feature

---

backend/src/CLI.ts

Hiding errors for cli version check that appear when updating from desktop 2.4.7 and cli 0.37.2 
1. Install Desktop 2.4.7-alpha (it's attached to the Jira ticket)
2. Wait for prompting and update to latest (must be at least 2.5.32)
3. See if any errors appear
<https://remoteit.atlassian.net/browse/DESK-564>

[DESK-564] Hide errors from cli version checking for 2.4.7 update path

---

backend/src/binaryInstaller.ts
backend/src/preferences.ts
src/AutoUpdater.ts

When the preference update was happening it was not updating the preference value in the ui, so when a preference was changed it was resetting the desktop version back to the old version.
1. Install previous version
2. Check the version in the preferences file
3. Update 
4. Check the version in the preferences file
5. Change the auto update setting
6. Recheck the version in the preferences file
Version should not have changed after switching the auto-update setting.
<https://remoteit.atlassian.net/browse/DESK-565>

[DESK-565] no quiet setting of preferences is allowable

---

frontend/src/components/OutOfBand/OutOfBand.tsx
frontend/src/models/devices.ts
frontend/src/pages/NetworkPage/NetworkPage.tsx
frontend/src/pages/SettingsPage/SettingsPage.tsx
frontend/src/pages/SetupServices/SetupServices.tsx

To increase visibility added OOB indicator to the device setup and the general settings pages.
1. Sign in to a remoteit Pi that has out of band activated
2. Configure for out of band mode ... needs two networks connected
3. You should see the indicator on the settings page, the device services setup page (after registered) and the network scan page.
<https://remoteit.atlassian.net/browse/DESK-562>

[DESK-562] OOB indicator on more pages

---

backend/src/Connection.ts
backend/src/cliStrings.ts

If failover hasn't been set, default it to true
1. Start with previous version of desktop
2. Start a new connection
3. Update to the latest version
4. You should see the proxy failover setting set to true
<https://remoteit.atlassian.net/browse/DESK-633>

[DESK-633] If failover hasn't been set, default it to true

---

backend/src/CLI.ts
backend/src/Connection.ts
backend/src/ConnectionPool.ts
backend/src/Controller.ts
frontend/src/components/ConnectionErrorMessage/ConnectionErrorMessage.tsx
frontend/src/pages/ServicePage/ServicePage.tsx

Removing access to logs, since we aren't getting logs from cli
Remove turning off auto start on disconnect. CLI reconnect behavior is different
Default to not connecting when reading cli connection state
Fix disconnected connection sort order
Under some circumstances with cli was exiting early we would read in the cli results before clearing the connection state. This fixes that issue.
<https://remoteit.atlassian.net/browse/DESK-634>

[DESK-634] clear connecting

---

backend/package-lock.json
backend/package.json
backend/src/Command.ts
backend/src/Installer.test.ts
backend/src/Installer.ts
backend/src/cliStrings.ts
backend/src/constants.ts
common/types.d.ts
frontend/package-lock.json
frontend/package.json
frontend/src/components/App/App.tsx
frontend/src/components/ScanNetwork/ScanNetwork.tsx
frontend/src/models/binaries.ts
frontend/src/pages/SettingsPage/SettingsPage.tsx
package-lock.json
package.json
src/TrayMenu.ts

CLI Version 1.3.0
Display the actually installed cli version instead of the desired
Fix broken icon display for Other network interface results
Fix parsing of caught cli errors
Add missing -j flag to remove command
1. Sign in
2. Go to settings page and see installed version of CLI
3. Update CLI to newer version outside of CLI
4. Close and restart CLI (or wait for hearbeat check )
<https://remoteit.atlassian.net/browse/DESK-637>

[DESK-637] show installed cli version

---

backend/src/CLI.ts
backend/src/Command.ts
backend/src/Connection.ts
backend/src/ConnectionPool.ts
common/types.d.ts

So that connection errors affect the connection object and the errors stay with the specific connection instead of just in the global messaging.
1. Sign in
2. Go to a bad connection and trigger a connection error ... ?
3. You should see the error in the main messaging but also see the connection go back offline and see the warning indicator witht the connection error message available.
<https://remoteit.atlassian.net/browse/DESK-641>

[DESK-641] Connection errors

---

backend/package-lock.json
backend/package.json
backend/src/CLI.ts
backend/src/Connection.ts
backend/src/ConnectionPool.ts
backend/src/Controller.ts
backend/src/electronInterface.ts
common/types.d.ts
frontend/package-lock.json
frontend/package.json
frontend/src/buttons/ForgetButton/ForgetButton.tsx
frontend/src/components/ConnectionsList/ConnectionsList.tsx
frontend/src/components/Header/Header.tsx
frontend/src/components/Router/Router.tsx
frontend/src/components/ServiceName/ServiceName.tsx
frontend/src/components/Title/Title.tsx
frontend/src/pages/LogPage/LogPage.tsx
frontend/src/pages/UsersPage/UsersPage.tsx
frontend/src/styling/theme.ts
package-lock.json
package.json
src/ElectronApp.ts
src/TrayMenu.ts

System tray menu improvements to limit number of connections or recent connections to 10 and provide a clear recent menu.
1. Sign in
2. Add 11 or more different connections
3. Look at the system tray menu. You should see up to 10 connections and recent connections. 
4. If more than 10 connections you should see a menu item that says "and X more..." 
5. If you click the more menu it should open the connections page in desktop
6. Clicking the X on the connections page to the right of recent should clear the recent connections
7. The same clear recent function is also available on the system tray menu.
<https://remoteit.atlassian.net/browse/DESK-584>

[DESK-584] Tray menu grouping

---

frontend/src/helpers/connectionHelper.ts

a fix to delete connections and avoid showing them on the connections list after a device is deleted
- [ x ] Pull Request title is in the format `[PROJ-12345] Some useful description here...`
- [ x ] I have added one or more reviewers
- [ x  ] This PR only contains one isolated change (bug fix, feature, etc)
- [ x ] I have manually reviewed this PR to make sure only the files I intended to change were changed and nothing else
- [ x ] I have notified reviewers on Slack by @ mentioning them in the `#desktop`channel
- [ x ] I have moved the Jira ticket into `Resolved` state and made a note in the ticket with a link to this PR
1. Sign in
2. Go to...
3. Click...

[DESK-276]

---

backend/src/CLI.ts
backend/src/binaryInstaller.test.ts
backend/src/binaryInstaller.ts
backend/src/constants.ts
common/types.d.ts
frontend/src/components/ServiceConnected/ServiceConnected.tsx
uninstaller.nsh

Show the connection type now available in CLI
Switch default of deregister command to no.
1. Sign in
2. Connect to a device
3. View the service detail page and see the connection type ie: "peer to peer"
<https://remoteit.atlassian.net/browse/DESK-680>
<https://remoteit.atlassian.net/browse/DESK-682>

[DESK-680][DESK-682] show conn type

---

backend/src/CLI.ts
frontend/src/helpers/connectionHelper.ts
frontend/src/models/devices.ts

Fixed cleaning orphaned connections
1. Sign in to an account with more than 50 devices
2. Connect to a device that you can later delete
3. Go delete that device you connected to
4. You should see the device and the connections made to it all disappear
5. Upon "loading more" devices in the device list all other connections should remain.
<https://remoteit.atlassian.net/browse/DESK-661>

[DESK-661] Remove deleted device connections

---

backend/src/ConnectionPool.ts

Hardening of connection initialization
1. Start with active connections in an older version of Desktop
2. Update desktop
3. On update you should not see errors where connections are trying to start before the CLI installation is complete
<https://remoteit.atlassian.net/browse/DESK-695>

[DESK-695] Hardening of connection initialization

---

backend/src/constants.ts

Install desktop Windows in other disk differents to C:/
https://remoteit.atlassian.net/browse/DESK-754
CLI is using the default DISK of Windows, checking with @codemodify 
1. Install desktop in Windows
2. Choose one disk different to C
3. You should see the working desktop
https://remoteit.atlassian.net/browse/DESK-754

[DESK-754] Windows install on other disk

---

frontend/src/components/ServiceForm/ServiceForm.tsx

1. Sign in to AWS ami
2. Go to add new service
3. Click save
4. You should see the service connection setting be locked to p2p only
<https://remoteit.atlassian.net/browse/DESK-802 >

DESK-802 p2p setting

---

backend/src/User.ts
backend/src/server.ts
frontend/src/models/auth.ts
frontend/src/services/Controller.ts

When auth times out on the backend the connection gets dropped and the desktop seems locked up.
We need to handle this scenario and return the user back to the login screen to re-try to auth.
1. Sign in on a timing out connection
2. You should see the sign in screen again upon failure.
<https://remoteit.atlassian.net/browse/DESK-863>

DESK-863 Timeout handling

---

backend/src/systemInfo.ts

/system requests by find.remote.it should return device.uid instead of device.name because it's no longer available in config.json
<https://remoteit.atlassian.net/browse/FIND-10>

FIND-10 /system requests by find.remote.it should return device.uid

---

frontend/src/components/InlineTemplateSetting/InlineTemplateSetting.tsx
frontend/src/components/PortSetting/PortSetting.tsx
frontend/src/components/ServiceForm/ServiceForm.tsx
frontend/src/helpers/connectionHelper.ts
frontend/src/pages/LanSharePage/LanSharePage.tsx

1. Sign in
2. Go to a device you own and go to the edit service screen
3. Click the default port field and set a default
4. You should see the port change in the url previews 
5. You should return to the connection page and see the default values
6. When you connect it should use the defaults.
<https://remoteit.atlassian.net/browse/DESK-949>

DESK-949 Fixing default port assignment

---

installer.nsh

Check the clean installation and update installation.
1. Install the old version Desktop
2. Register device and make some P2P connections
3. Update to the new version (that is applied this change)
4. Verify that the configuration files (tareget / connection setting) is located in the backup directory
<https://remoteit.atlassian.net/browse/DESK-939>

[DESK-939] Installer should not move config on init

---

frontend/src/pages/LanSharePage/LanSharePage.tsx

Bind IP Address doesn't change on LAN sharing page when settings changed.
1. Sign in
2. Go to...
3. Click...
https://remoteit.atlassian.net/browse/DESK-975

[DESK-975] fix state bind ip

---

backend/package-lock.json
backend/package.json
backend/src/ConnectionPool.ts
backend/src/cli-version.json
backend/src/sharedCopy/applications.ts
frontend/package-lock.json
frontend/package.json
frontend/src/buttons/ConnectButton/ConnectButton.tsx
frontend/src/buttons/ResetButton/ResetButton.tsx
frontend/src/components/AdminPanelConnect.tsx
frontend/src/components/ConnectionStateIcon/ConnectionStateIcon.tsx
frontend/src/components/InlineSetting/InlineSetting.tsx
frontend/src/components/InlineTemplateSetting/InlineTemplateSetting.tsx
frontend/src/components/LocationPin.tsx
frontend/src/components/PortSetting/PortSetting.tsx
frontend/src/components/Quote.tsx
frontend/src/shared/applications.ts
installer.nsh
package-lock.json
package.json

1. Fix event canceling for save inline edit fields
2. sessionid connection state updates
3. Fix reset to default values for inlline edit fields
4. Remove unused imports
5. Adding missed location pin component
6. Fixing copy icon spacing
7. updating CLI to 1.6.39
1. Sign in
2. Go to a service page
3. Click an inline edit field, edit the content then slow-click the save icon
4. You should see it save.
<https://remoteit.atlassian.net/browse/DESK-977>

DESK-977 inline edit update

---

frontend/src/buttons/RestoreButton.tsx
frontend/src/components/DeviceList/DeviceList.tsx
frontend/src/components/DeviceSetupItem/DeviceSetupItem.tsx
frontend/src/models/ui.ts
frontend/src/pages/DevicesPage/DevicesPage.tsx
frontend/src/routers/Router.tsx

1. Sign in on a system without a device
2. Click restore button
3. Click the "Register services" button instead of restoring
4. You should see the setup screen and then after finished should see the device list as normal, not in the restore state.
<https://remoteit.atlassian.net/browse/DESK-997 >

DESK-997 Changing restore state from model to route

---

backend/src/preferences.ts
common/types.d.ts
frontend/src/pages/SettingsPage/SettingsPage.tsx
src/AutoUpdater.ts

check-update version also using beta  and alpha
`semverCompare` avoid check version if the current version is alpha o beta
before to compare, this change is sending just version without `alpha` or `beta`
1. Use a version alpha or beta newest than the last stable release
2. You should not see a modal to update
https://remoteit.atlassian.net/browse/DESK-1038

[DESK-1013] check update version beta alpha

---

frontend/src/models/shares.ts

avoid re-share user
1. Sign in
2. Go to device service
3. Click share users
4. Add one that you had shared
4. You should not see error
https://remoteit.atlassian.net/browse/DESK-1071

[DESK-1071] avoid re share user

---

src/ElectronApp.ts

So, when you will receive a toaster notification, you will see Remote.it app name and icon,
- [ x ] This PR only contains one isolated change (bug fix, feature, etc) (yes, as far I know)
- [ x ] I have manually reviewed this PR to make sure only the files I intended to change were changed and nothing else
1. Go on a Windows 10 computer
2. Put a shortcut of Electron.exe (in `node_modules\electron\dist\electron.exe`) in your start menu, then give him as name: "Remote.it" and as logo a Remote.it Logo
3. Start the app then open Devtools
4. Type
```js
new Notification("Test")
```
5. You should see as Notification name "Remote.it" and as logo, the logo of Remote.it
Thank you for making that awesome software :)

Fix name and icon for notification

---

common/types.d.ts
frontend/src/components/EventList/EventMessage.tsx

1. Sign in
2. Go to user logs
3. . You should see correctly the logs
https://remoteit.atlassian.net/browse/DESK-1132
[DESK-1132]: https://remoteit.atlassian.net/browse/DESK-1132

[DESK-1132] show name device in user logs

---

frontend/src/components/SharedUsersList/SharedUsersList.tsx

[DESK-1172] cannot see users shared
1. Sign in
2. Go to...
3. Click...
https://remoteit.atlassian.net/browse/DESK-1172
[DESK-1172]: https://remoteit.atlassian.net/browse/DESK-1172

[DESK-1172] cannot see users shared

---

src/ElectronApp.ts

When you package your app, if you got a notification on a windows 10, it will show as app name "it.remote.desktop". This is a fix for this bug
1. Package your app for Windows
2. Run the packaged app from a Windows computer
3. Make a notification using devtools
4. See the changes

Fixing Notification Name when app is packaged

---

frontend/src/helpers/apiHelper.ts

https://pretagteam.com/question/cannot-access-authreducer-before-initialization
[](https://pretagteam.com/question/cannot-access-authreducer-before-initialization)
https://github.com/remoteit/desktop/blob/df300c19f9291a47992dfb082f8932e389cc3c97/frontend/src/services/remote.it.ts
it is getting an error with node14 on Ubuntu

[DESK-0000] fix before initialization unix URL

---

frontend/src/components/Attributes.tsx
frontend/src/components/ServiceForm/ServiceForm.tsx

1. Clear service form error message on init. 
2. Also only show Access attributes in device list
<https://remoteit.atlassian.net/browse/DESK-1266>

DESK-1266 Clear service form error message on init

---

frontend/src/components/PlanCheckout.tsx
frontend/src/models/organization.ts
frontend/src/models/plans.ts
frontend/src/pages/OrganizationAddPage.tsx
frontend/src/services/cloudController.ts

Refresh org data so we have the roles on a new org.
Fix the existing subscription detection so that new users can subscribe
wait for plan to be fully update after purchase update
<https://remoteit.atlassian.net/browse/DESK-1438>
<https://remoteit.atlassian.net/browse/DESK-1439>
<https://remoteit.atlassian.net/browse/DESK-1440>
<https://remoteit.atlassian.net/browse/DESK-1442>

DESK-1438 DESK-1439 DESK-1440 DESK-1442 Refresh data after creating a new org

---

backend/package-lock.json
backend/package.json
backend/src/ConnectionPool.ts
frontend/package-lock.json
frontend/package.json
frontend/src/buttons/AddUserButton/AddUserButton.tsx
frontend/src/buttons/ErrorButton/ErrorButton.tsx
frontend/src/components/Connect.tsx
frontend/src/components/DeviceHeaderMenu.tsx
frontend/src/components/Header/Header.tsx
frontend/src/components/NetworkListItem.tsx
frontend/src/components/NetworksAccordion.tsx
frontend/src/components/ServiceHeaderMenu.tsx
frontend/src/components/SharedUsersLists.tsx
frontend/src/components/SidebarNav.tsx
frontend/src/helpers/connectionHelper.ts
frontend/src/models/devices.ts
frontend/src/pages/ConnectionPage.tsx
frontend/src/pages/DevicePage.tsx
frontend/src/pages/ServiceConnectPage.tsx
frontend/src/pages/SharePage/SharePage.tsx
frontend/src/routers/DeviceRouter.tsx
installer.nsh
package-lock.json
package.json

- GQL-252 get device access users as well as organization guests
- DESK-1613 disable adding organization member unless you have admin permission
- Remove device name from header
- Update share button to say Share to guest
- Change display of unauthorized if device not loaded to loading screen
- Update active connection counting logic
- Ensure connection device data is pulled from the active account
- Improved connection certificate error message
- Improved details why you can't add a service to a network

GQL-252 DESK-1613 test bugs

---

backend/package-lock.json
backend/package.json
frontend/package-lock.json
frontend/package.json
frontend/src/components/Breadcrumbs/Breadcrumbs.tsx
frontend/src/components/PermissionsList.tsx
frontend/src/components/RoleSelect.tsx
frontend/src/components/ServiceContextualMenu/ServiceContextualMenu.tsx
frontend/src/components/ServiceForm/ServiceForm.tsx
frontend/src/helpers/connectionHelper.ts
frontend/src/models/devices.ts
frontend/src/models/organization.ts
frontend/src/pages/LanSharePage/LanSharePage.tsx
frontend/src/pages/NetworkPage.tsx
frontend/src/pages/OrganizationRolePage.tsx
installer.nsh
package-lock.json
package.json

- Safeguarding service and device updates to other copies of the same device
- Update role page layout
- Display select an item if no network
- Add lock icon to system roles in dropdowns
- Move service host into the editable section so it does not display if the device isn't cloud controlled

3.12 release

---

common/types.d.ts
frontend/src/components/Connect.tsx
frontend/src/components/DeleteDevice.tsx
frontend/src/components/DeviceHeaderMenu.tsx
frontend/src/components/DeviceTagEditor.tsx
frontend/src/components/ListHorizontal.tsx
frontend/src/components/ServiceName/ServiceName.tsx
frontend/src/models/accounts.ts
frontend/src/models/backend.ts
frontend/src/models/devices.ts
frontend/src/models/networks.ts
frontend/src/models/ui.ts
frontend/src/pages/ConnectionPage.tsx
frontend/src/pages/DevicePage.tsx
frontend/src/routers/DeviceRouter.tsx
frontend/src/services/cloudController.ts

- Loaded state out of sync
- Fix detection of unauthorized device access
- Display newly registered devices at top of device list with a new indicator
- Disable connection button instead of putting into loading state before data loaded
- Move device tagging to device page from device details header for better visibility
<https://remoteit.atlassian.net/browse/DESK-1623>

DESK-1623 Loaded state + tweaks
