remoteit/desktop

backend/src/Application.ts, backend/src/CLI.ts, backend/src/Connection.ts, backend/src/Controller.ts, backend/src/Server.ts, backend/src/constants.ts, backend/src/index.ts, readme.md
I want to merge this into master to pull it into another branch. Dev will continue for this ticket however.
=> DESK-327 Capture and log server start errors as well as displaying most errors in app

backend/package-lock.json, backend/package.json, frontend/package-lock.json, frontend/package.json, frontend/src/buttons/ConnectButton/ConnectButton.tsx, frontend/src/buttons/DynamicButton/DynamicButton.tsx, package-lock.json, package.json
=> DESK-350 connect button loading state

backend/src/Application.ts, backend/src/Command.ts, backend/src/Controller.ts, backend/src/index.ts
So we can attempt to filter out the heartbeat errors.
=> DESK-370 Clearer airbrake messages

backend/package-lock.json, backend/package.json, frontend/package-lock.json, frontend/package.json, frontend/src/components/App/App.tsx, frontend/src/models/auth.ts, frontend/src/pages/DevicesPage/DevicesPage.tsx, frontend/src/pages/Page/Page.tsx, frontend/src/services/Controller.ts, package-lock.json, package.json
Reconnect the UI if disconnected unintentionally.
=> DESK-363 sleep reconnect

frontend/src/components/AutoStartSetting/AutoStartSetting.tsx, package-lock.json, package.json
https://remoteit.atlassian.net/browse/DESK-369
=> [DESK-369] rename restart to reconnect on disconnect

backend/src/Application.ts, backend/src/CLI.ts, backend/src/Connection.ts, backend/src/Installer.ts, backend/src/binaryInstaller.ts, backend/src/environment.ts
Preparing desktop for beta release. Backing out cli install at user level.
<https://remoteit.atlassian.net/browse/DESK-206>
=> [DESK-206] Only install cli as admin user

backend/package-lock.json, backend/package.json, backend/src/Application.ts, backend/src/CLI.ts, backend/src/Connection.ts, backend/src/Controller.ts, backend/src/Installer.ts, backend/src/binaryInstaller.ts, backend/src/environment.ts, backend/src/server.ts, frontend/package-lock.json, frontend/package.json, frontend/src/components/App/App.tsx, frontend/src/components/RemoteHeader/RemoteHeader.tsx, frontend/src/components/Setup/Setup.tsx, frontend/src/models/backend.ts, frontend/src/models/devices.ts, frontend/src/pages/Page/Page.tsx, frontend/src/services/Controller.ts, package-lock.json, package.json
Improved first run experience based on feedback from pi setup testing
Also re-bind backend websockets on app sleep
<https://remoteit.atlassian.net/browse/DESK-378>
<https://remoteit.atlassian.net/browse/DESK-377>
=> [DESK-377] [DESK-378] setup first run experience & rebind sockets on sleep

backend/package-lock.json, backend/package.json, backend/src/Application.ts, backend/src/CLI.ts, backend/src/Controller.ts, backend/src/binaryInstaller.test.ts, backend/src/binaryInstaller.ts, backend/src/cliInterface.ts, frontend/package-lock.json, frontend/package.json, frontend/src/components/Body/Body.tsx, frontend/src/components/InstallationNotice/InstallationNotice.tsx, frontend/src/components/Logo/Logo.tsx, frontend/src/components/Setup/Setup.tsx, frontend/src/index.tsx, package-lock.json, package.json
Changed the install process to happen after installation. This is backing out changes made to install at user level silently and for the new websocket system service.
Also refactored out the array of installers support in favor of simpler singler installer.
Also confirmed that DESK-206 is now working.
1. Sign in
2. Go to settings page and scroll up to the uninstall menu
3. Uninstall
4. Confirm all files removed 
5. If needed reference this doc for file locations:
https://docs.google.com/spreadsheets/d/1cTPoTHsoulcMeED_Sq7cZHXYctL7ymbMBLTCHSvFA6c/edit#gid=1157351303
6. Restart and signin
7. Confirm network scan and initiator connection works.
8. repeat steps 2 - 6 once more with new app
https://remoteit.atlassian.net/browse/DESK-206
https://remoteit.atlassian.net/browse/DESK-379
=> [DESK-379] [DESK-206] install after signin

src/TrayMenu.ts
Fixed - tray menu disconnect reconnects
1. Sign in
2. connect to a service
3. disconnect from the system tray
4. wait a minute or two and make sure it doesn't restart.
<https://remoteit.atlassian.net/browse/DESK-364>
=> [DESK-364] tray disconnect reconnecting

.circleci/config.yml, backend/package-lock.json, backend/package.json
Tring to get circleci integration working
...
Did it!
=> Circleci test integration

backend/src/binaryInstaller.ts, backend/src/constants.ts
On windows check for old cli and stop any services that may have been running
See Ticket
<https://remoteit.atlassian.net/browse/DESK-383>
=> [DESK-383] stopping services running on deprecated cli

backend/package-lock.json, backend/package.json, backend/src/Connection.ts, frontend/package-lock.json, frontend/package.json, frontend/src/constants.ts, frontend/src/models/auth.ts, frontend/src/pages/Page/Page.tsx, frontend/src/services/Controller.ts, package-lock.json, package.json
On error keep retrying to reconnect to the backend websocket. 
I've also provided a manual retry button in the disconnected message since I've set the retry interval to 20 seconds.
Added test plan to ticket <https://remoteit.atlassian.net/browse/DESK-378>
<https://remoteit.atlassian.net/browse/DESK-378>
<https://remoteit.atlassian.net/browse/DESK-356>
=> [DESK-378] [DESK-356] Reconnect windows frontend

frontend/src/components/Icon/Icon.tsx, frontend/src/components/InstallationNotice/InstallationNotice.tsx
Previous text was too brief in testing.
1. delete the remoteit cli
2. restart in user mode
3. view install dialog
4. understand words
<https://remoteit.atlassian.net/browse/DESK-388>
=> [DESK-388] install screen text update

backend/__mocks__/fs.ts, backend/src/Application.ts, backend/src/Installer.test.ts, backend/src/Installer.ts
Update to allow cli install without prompting if running as root/admin.
Unit tests.
1. Delete cli 
2. Start app as root/admin as described in readme
2. See that cli is now installed without propt
<https://remoteit.atlassian.net/browse/DESK-387>
=> [DESK-387] Auto install cli if run as admin. Unit tests.

backend/package-lock.json, backend/package.json, frontend/package-lock.json, frontend/package.json, frontend/src/components/Setup/Setup.tsx, frontend/src/pages/SetupPage/SetupPage.tsx, package-lock.json, package.json
Protect users from duplicate device name errors before submitting the form.
1. Sign in
2. Try to enter a name that is already registered in your account
3. Shared devices don't count
4. Case insensitive
<https://remoteit.atlassian.net/browse/DESK-385>
=> [DESK-385] Do not allow duplicate device names to be registered

backend/src/remoteitInstaller.ts
Upgrade cli to v1.0.1
https://remoteit.atlassian.net/wiki/spaces/PLAN/pages/271319256/Desktop+Test+Plan+v2.5.x
<https://remoteit.atlassian.net/browse/DESK-392>
=> [DESK-392] Upgrade cli to v1.0.1

frontend/src/components/App/App.tsx, frontend/src/pages/Page/Page.tsx
Indicate if another user is logged in on the login screen as an error
1. Sign in
2. Go to...
3. Click...
<https://remoteit.atlassian.net/browse/DESK-400>
=> [DESK-400] Indicate if another user is logged in

backend/src/Installer.ts, backend/src/constants.ts, backend/src/remoteitInstaller.ts, common/types.d.ts, frontend/src/buttons/LaunchButton/LaunchButton.tsx, frontend/src/components/Icon/Icon.tsx, frontend/src/components/InlineSetting/InlineSetting.tsx, frontend/src/components/LaunchSetting/LaunchSetting.tsx, frontend/src/components/LaunchSetting/index.ts, frontend/src/index.tsx, frontend/src/pages/ServicePage/ServicePage.tsx, frontend/src/pages/ServicesPage/ServicesPage.tsx, frontend/src/services/applications.ts, package-lock.json
Added a simple basic interface for editing the tokenized launch url.
1. Sign in
2. Navigate to a service detail page
3. Click the Launch URL 
4. you should be able to edit the url and token
5. You should see the tokens listed under the "?" hoverstate
6. Connect
7. Launch the connection with the edited url
8. Test the launch url for ssh with username
<https://remoteit.atlassian.net/browse/DESK-163>
<https://remoteit.atlassian.net/browse/DESK-249>
=> [DESK-163][DESK-249] Provide interface to edit launch url path

frontend/src/components/Target/Target.tsx
Disable submit until there is a service name.
1. Sign in
2. Try to add a service to a hosted system without a name
3. Fail.
<https://remoteit.atlassian.net/browse/DESK-396]>
=> [DESK-396] disable service form submit until name exists

frontend/src/components/Header/Header.tsx, frontend/src/pages/SetupPage/SetupPage.tsx
Add guest view banner to make it more clear that you are a guest.
- [] ~~Translation strings added/updated for all user-visible text~~
1. Sign in to a device as a user that didnt' register the device.
2. View the hosted tab
3. Be amazed by the blue banner and guest text in the header.
<https://remoteit.atlassian.net/browse/DESK-402>
=> [DESK-402] Adding guest view indicators to UI

frontend/src/components/Setup/Setup.tsx
1. Sign in
2. Go to Hosted tab
3. Enter a bad char. 
4. See warning, but be able to submit
5. Check duplicate names still block registering.
<https://remoteit.atlassian.net/browse/DESK-394>
=> [DESK-394] don't disable register button on bad char

backend/src/binaryInstaller.ts
1. Do it fast on a slow machine and no errors.
<https://remoteit.atlassian.net/browse/DESK-387>
=> [DESK-387] Protect against running install while installing

frontend/src/components/LoadingMessage/LoadingMessage.tsx, frontend/src/components/ScanNetwork/ScanNetwork.tsx, frontend/src/components/SignInForm/SignInForm.tsx, frontend/src/index.tsx
Desktop usernames not case insensitive. 
This prevents a user from logging in if case isn't matched. Must be case insensitive.
1. Sign in to the desktop as one user with capitol letters
2. Go to localhost:29999 and try to sign in with the same username with lowercase letters
3. You should get in still
<https://remoteit.atlassian.net/browse/DESK-422>
=> [DESK-422] lowercase usernames so that user input is case insensitive

backend/src/Connection.ts, frontend/src/buttons/ErrorButton/ErrorButton.tsx, frontend/src/components/ConnectionErrorMessage/ConnectionErrorMessage.tsx, frontend/src/components/ServiceListItem/ServiceListItem.tsx, frontend/src/components/Targets/Targets.tsx, frontend/src/constants.ts, frontend/src/models/logs.ts, frontend/src/pages/ServicePage/ServicePage.tsx, frontend/src/services/Controller.ts
Improved connection error notices. See test plan and issues for details.
1. Sign in
2. Physically disconnect the remote device
3. Connect to the disconnected device
4. Wait for failure
5. Error should be visible without hover
6. Error should link to log page where it was logged
7. Error should be red
8. Reconnect the remote device
9. Wait and then reconnect
10. Error message should disappear
<https://remoteit.atlassian.net/browse/DESK-317>
<https://remoteit.atlassian.net/browse/DESK-318>
<https://remoteit.atlassian.net/browse/DESK-354>
<https://remoteit.atlassian.net/browse/DESK-361>
=> [DESK-317][DESK-318][DESK-354][DESK-361] Connection error improvements

backend/src/Application.ts
Trying to make Admin launch smooth on a slower windows machine.
1. Uninstall completely
2. Run as admin
3. Startup smoothly
4. Able to add new device
<https://remoteit.atlassian.net/browse/DESK-387>
=> [DESK-387] Don't block startup for installation

backend/src/Controller.ts, frontend/src/components/Setup/Setup.tsx, frontend/src/components/SetupView/SetupView.tsx, frontend/src/components/SetupView/index.ts, frontend/src/models/backend.ts, frontend/src/pages/SetupPage/SetupPage.tsx, frontend/src/services/Controller.ts
Disabled hosted tab if remote and not running with elevated permissions. This can't work because it requires answering system prompts.
1. Startup desktop without admin/sudo
2. Register the device along with it's own admin panel
3. Connect remotely to the device
4. View the hosted panel
Hosted panel should not be editable and should have a message telling what's going on.
<https://remoteit.atlassian.net/browse/DESK-421>
=> [DESK-421] Disable hosted if remote and not running with elevated permissions

backend/src/CLI.ts, backend/src/Controller.ts, backend/src/User.ts, backend/src/server.ts
Allow device owner to always log in, kicking out other users.
1. Login and register the system as user 1
2. Open http://localhost:29999 or connect remotely
3. Try to login as user 2 - get denied
4. Log out of user 1
5. Log in with user 2
6. Try to login with user 1 (Device owner) and succeed
User 2 should have been kicked out.
<https://remoteit.atlassian.net/browse/DESK-429>
=> [DESK-429] Allow device owner to always log in

backend/package-lock.json, backend/package.json, backend/src/Connection.ts, backend/src/LAN.ts, backend/src/index.ts, frontend/package-lock.json, frontend/package.json, frontend/src/buttons/CopyButton/CopyButton.tsx, frontend/src/components/HostSetting/HostSetting.tsx, frontend/src/helpers/nameHelper.ts, frontend/src/services/applications.ts, package-lock.json, package.json
Setting localhost as the text in launch url and where possible.
Fixed CLI event error that was blocking build.
Internal release version bump.
1. Sign in
2. Go to a device's service detail page
3. See the Launch URL with the word localhost instead of 127.0.0.1
4. Confirm it's the same for copy or launch url
<https://remoteit.atlassian.net/browse/DESK-423>
=> [DESK-423] Localhost name

frontend/src/buttons/CopyButton/CopyButton.tsx, frontend/src/buttons/LaunchButton/LaunchButton.tsx, frontend/src/components/Setup/Setup.tsx, frontend/src/services/applications.ts
Copy url should only copy the host:port
1. Sign in
2. Go to service
3. Connect to RDP or VNC
4. Copying should copy only host:port and not include the scheme
<https://remoteit.atlassian.net/browse/DESK-432>
<https://remoteit.atlassian.net/browse/DESK-423>
<https://remoteit.atlassian.net/browse/DESK-424>
=> [DESK-424][DESK-423][DESK-432] Fix copy links and text enhancements

frontend/src/components/Scan/Scan.tsx
Default to the active network interface in the scan UI
1. Sign in
2. Go to network scan page with two interfaces
3. The default selection should be the active interface
<https://remoteit.atlassian.net/browse/DESK-404>
=> [DESK-404] Default the active network interface

backend/package-lock.json, backend/package.json, backend/src/binaryInstaller.test.ts, backend/src/binaryInstaller.ts, backend/src/constants.ts, frontend/package-lock.json, frontend/package.json, package-lock.json, package.json, src/AutoUpdater.ts
1. Start with an older alpha version of desktop
2. Register the device and a service
3. Go through the auto-update process
4. Confirm the device and services are still available by connecting from a remote system
<https://remoteit.atlassian.net/browse/DESK-431>
=> [DESK-431] Services restart

backend/src/binaryInstaller.test.ts, backend/src/binaryInstaller.ts, backend/src/constants.ts
Move windows bin location to \remoteit-bin
1. install
2. check bin install location
<https://remoteit.atlassian.net/browse/DESK-445>
=> [DESK-445] Move windows bin location to \remoteit-bin

backend/scripts/remoteit-headless.service
Adding service script for RPi headless support
1. build headless
2. script should be in package in `package/scripts`
<https://remoteit.atlassian.net/browse/DESK-444>
=> [DESK-444] adding service script for RPi headless support

backend/src/binaryInstaller.ts, backend/src/constants.ts, backend/src/environment.ts, backend/src/index.ts, backend/src/systemInfo.ts, src/AutoUpdater.ts
Add mac only path support and change unix bin path
On linux it should install binaries in `/usr/bin`
On mac it should install binaries in `/usr/local/bin`
On windows it should install binaries in `/Program Files/remoteit-bin`
It should also clean up 
On windows `/Program Files/remoteit/remoteit.exe` and  `/Windows/remoteit.exe`
On linux `/usr/local/bin/remoteit`
<https://remoteit.atlassian.net/browse/DESK-441>
=> [DESK-441] Add mac only path support and change unix bin path

backend/package-lock.json, backend/package.json, backend/src/constants.ts, frontend/package-lock.json, frontend/package.json, package-lock.json, package.json
=> 2.5.24-alpha.4 Version Bump

frontend/src/components/App/App.tsx, frontend/src/components/Header/Header.tsx, frontend/src/components/UninstallSetting/UninstallSetting.tsx, frontend/src/hooks/usePermissions.ts, frontend/src/pages/SettingsPage/SettingsPage.tsx, frontend/src/pages/SetupPage/SetupPage.tsx
Disable uninstall, reinstall and quit for guest users.
Create usePermissions hook and apply permissions to menus
1. Sign in as a guest (register the system with another user)
2. Go to the settings page
3. See that you can't uninstall or reinstall or quit
<https://remoteit.atlassian.net/browse/DESK-438>
=> [DESK-438] Create usePermissions hook and apply permissions to menus

backend/src/CLI.ts, backend/src/Controller.ts, backend/src/LAN.ts, backend/src/Logger.ts, backend/src/cliInterface.ts, backend/src/environment.ts, common/types.d.ts, frontend/src/components/App/App.tsx, frontend/src/components/Breadcrumbs/Breadcrumbs.tsx, frontend/src/components/DeviceSetupItem/DeviceSetupItem.tsx, frontend/src/components/LocalhostScanForm/LocalhostScanForm.tsx, frontend/src/components/LocalhostScanForm/index.ts, frontend/src/components/Network/Network.tsx, frontend/src/components/ScanNetwork/ScanNetwork.tsx, frontend/src/components/Setup/Setup.tsx, frontend/src/components/SetupView/SetupView.tsx, frontend/src/components/UninstallSetting/UninstallSetting.tsx, frontend/src/constants.ts, frontend/src/helpers/nameHelper.ts, frontend/src/hooks/usePermissions.ts, frontend/src/index.tsx, frontend/src/models/backend.ts, frontend/src/pages/LanSharePage/LanSharePage.tsx, frontend/src/pages/NetworkPage/NetworkPage.tsx, frontend/src/pages/Page/Page.tsx, frontend/src/pages/SetupPage/SetupPage.tsx, frontend/src/services/Controller.ts, frontend/src/services/serviceTypes.ts, readme.md
To support single click registration of the device and local services quick and easy.
1. Start up desktop with elevated permissions
2. Go to find.remote.it and find the system
3. Click connect
4. Login
5. You should land on the device setup screen
6. The hostname should be in the device name field
7. All local services should appear in a checked state
8. Click on the register button
9. Spinner should spin
10. Page should change and confirmation snackbar message should appear
11. After a minute, your device should appear in the device list
<https://remoteit.atlassian.net/browse/DESK-463>
=> [DESK-463] One click registration

backend/src/binaryInstaller.test.ts, backend/src/binaryInstaller.ts
1. Setup device on version 2.4.7 of desktop
2. Update the application
3. See if the services will restart on update.
<https://remoteit.atlassian.net/browse/DESK-484>
=> [DESK-484] cli installation and update logic with kill-all services

frontend/src/components/ConnectionsList/ConnectionsList.tsx, frontend/src/components/DeviceList/DeviceList.tsx, frontend/src/components/DeviceListEmpty/DeviceListEmpty.tsx, frontend/src/components/DeviceListEmpty/index.ts, frontend/src/components/DeviceSetupItem/DeviceSetupItem.tsx
1. Sign in with an account that has no devices
2. See the button to setup your device
3. profit.
<https://remoteit.atlassian.net/browse/DESK-492>
=> [DESK-492] Adding empty state action to device list

backend/src/Installer.ts, backend/src/binaryInstaller.ts, frontend/src/helpers/nameHelper.ts, src/AutoUpdater.ts
Sanatize hostname and fix auto update polling time
1. Sign in
2. Go to setup page
3. See if your devicename is free of dots
<https://remoteit.atlassian.net/browse/DESK-495>
=> [DESK-495] Sanatize hostname and fix auto update polling time

backend/package-lock.json, backend/package.json, frontend/package-lock.json, frontend/package.json, frontend/src/components/Setup/Setup.tsx, package-lock.json, package.json
Disable register button
1. Sign in
2. Register a device
3. Register button should be disabled upon click
<https://remoteit.atlassian.net/browse/DESK-498>
=> [DESK-498] Disable register button

backend/package-lock.json, backend/package.json, backend/src/CLI.ts, backend/src/constants.ts, frontend/package-lock.json, frontend/package.json, frontend/src/components/ConnectionsList/ConnectionsList.tsx, frontend/src/components/DataDisplay/DataDisplay.tsx, frontend/src/components/DocsLinks/DocsLinks.tsx, frontend/src/components/DocsLinks/index.tsx, frontend/src/components/LocalhostScanForm/LocalhostScanForm.tsx, frontend/src/components/Scan/Scan.tsx, frontend/src/index.tsx, frontend/src/pages/SetupDevice/SetupDevice.tsx, frontend/src/pages/SetupServices/SetupServices.tsx, frontend/src/pages/SetupSuccess/SetupSuccess.tsx, frontend/src/pages/SetupView/SetupView.tsx, frontend/src/pages/SetupWaiting/SetupWaiting.tsx, package-lock.json, package.json
**This PR contains a few fixes:**
Wording and docs link changes
Fix CLI logout detection not seeing device delete
Auto-start scanning on network page
Add loading state for localhost service scan
CLI version 1.1.6
Changes can be seen on an empty connections tab, and durring a new device registration.
<https://remoteit.atlassian.net/browse/DESK-504>
<https://remoteit.atlassian.net/browse/DESK-500>
=> [DESK-504][DESK-500] Docs links

backend/package-lock.json, backend/package.json, backend/src/Application.ts, backend/src/Connection.ts, backend/src/Controller.ts, backend/src/constants.ts, backend/src/electronInterface.ts, backend/src/environment.ts, backend/src/types.d.ts, common/types.d.ts, frontend/package-lock.json, frontend/package.json, frontend/src/services/Controller.ts, package-lock.json, package.json
To track initiator connections through connectd
Also to handle when partial data is put into the manufacturer.json
1. Log into Segment and go the the debug panel for desktop
2. Click something like starting a connection
3. See the data reported into Segment and notice if it is correct
<https://remoteit.atlassian.net/browse/DESK-490>
<https://remoteit.atlassian.net/browse/DESK-521>
=> [DESK-490][DESK-521] Initiator tracking and manufacturer data handling

backend/src/Command.ts, backend/src/sudoPromise.ts, backend/src/types.d.ts, frontend/src/pages/SetupWaiting/SetupWaiting.tsx
Display and parse cli stderr results
1. Sign in
2. Go to settings > setup device
3. Register a device name with another system
4. Don't refresh your device list
5. Try and register the same device name
6. View error about duplicate device name
<https://remoteit.atlassian.net/browse/DESK-529>
=> [DESK-529] Display and parse cli stderr results

backend/src/CLI.ts, backend/src/Connection.ts, backend/src/constants.ts, backend/src/environment.ts, common/types.d.ts, frontend/src/helpers/Analytics.ts, frontend/src/models/backend.ts
Update format of analytics data.  Update to use new Application code for headless and standard desktop.  Clean unwanted data from page views.
Use Desktop App.  View events and page views in segment.io
https://remoteit.atlassian.net/browse/DESK-531
https://remoteit.atlassian.net/browse/DESK-528
https://remoteit.atlassian.net/browse/DESK-489
=> [DESK-489][DESK-528][DESK-531] Update format of analytics data, update appCode, clean unwanted data

backend/src/User.ts, frontend/src/components/App/App.tsx, frontend/src/models/auth.ts, src/ElectronApp.ts
Electron app authenticates without passing credentials in the url
1. open the remote.it app
2. go to the webpage: http://localhost:29999
3. login in the browser
4. quit the app
5. launch the app and you should be auto-signed in
<https://remoteit.atlassian.net/browse/DESK-530>
=> [DESK-530] don't pass credentials in url

backend/package-lock.json, backend/package.json, backend/src/Installer.ts, backend/src/constants.ts, frontend/package-lock.json, frontend/package.json, package-lock.json, package.json
Release update. Minor issues with changing download url.
=> Desktop v2.5.25 with CLI v1.2.1

backend/src/Installer.ts, backend/src/binaryInstaller.ts
Added await to the cli current check.
See https://github.com/remoteit/desktop/pull/135 for test plan
<https://remoteit.atlassian.net/browse/DESK-552>
=> [DESK-552] Fixed cli update missing await on update detection

frontend/src/pages/SignInPage/SignInPage.tsx
Show message in headless sign-in regarding in-browser security message.
1. Visit a remote or local desktop in a browser that isn't using localhost or 127.0.0.1
2. ie: `http://192.168.0.152:29999`
3. Read messaging and check links
<https://remoteit.atlassian.net/browse/DESK-549>
=> [DESK-549] updating ssl sign in messaging

backend/package-lock.json, backend/package.json, frontend/package-lock.json, frontend/package.json, frontend/src/components/LanShareSelect/LanShareSelect.tsx, frontend/src/helpers/nameHelper.ts, package-lock.json, package.json
Replace usage of 0.0.0.0 with local IP address
1. Sign in
2. Go to a service detail page
3. Select Local Network Sharing
4. Enable LAN sharing
5. Connect
6. Copy the connection url or launch
7. The address should be the local IP address
8. It should not be 0.0.0.0
<https://remoteit.atlassian.net/browse/DESK-541>
=> [DESK-541] Replace usage of 0.0.0.0 with local IP address

backend/src/CLI.ts, backend/src/LAN.ts, backend/src/binaryInstaller.ts
Support missing ipMask and improve error messaging for scanning
1. Turn off network access
2. Go to network scan page
3. Click scan
4. You should see a message saying to check your network connection.
... IDK now to reproduce the missing ipMask, but I did but in handling for a missing one.
<https://remoteit.atlassian.net/browse/DESK-546>
=> [DESK-546] Support missing ipMask and improve error messaging

frontend/src/buttons/ConnectButton/ConnectButton.tsx, frontend/src/buttons/DeleteButton/DeleteButton.tsx, frontend/src/buttons/DynamicButton/DynamicButton.tsx, frontend/src/components/ConnectingAnimation/ConnectingAnimation.tsx, frontend/src/components/ConnectingAnimation/index.ts, frontend/src/components/Network/Network.tsx, frontend/src/components/NewTarget/NewTarget.tsx, frontend/src/components/Scan/Scan.tsx, frontend/src/components/ScanNetwork/ScanNetwork.tsx, frontend/src/components/ServiceConnected/ServiceConnected.tsx, frontend/src/components/ServiceListItem/ServiceListItem.tsx, frontend/src/components/Target/Target.tsx, frontend/src/components/Targets/Targets.tsx, frontend/src/components/UninstallSetting/UninstallSetting.tsx, frontend/src/models/backend.ts, frontend/src/models/devices.ts, frontend/src/models/ui.ts, frontend/src/pages/NetworkPage/NetworkPage.tsx, frontend/src/pages/Page/Page.tsx, frontend/src/pages/SetupServices/SetupServices.tsx, frontend/src/services/Controller.ts
Moved page state in scanning and device setup to the application level, so that it's retained across page changes and should be protected from users accidentally or mistakenly seeing wrong state.
1. Sign in
2. Register a device, or use an already registered device
3. Add and remove services manually and with the network scan
4. Change pages while in progress
5. The state should be retained even when going to a new page and returning
<https://remoteit.atlassian.net/browse/DESK-542>
=> [DESK-542] Application level state

frontend/src/components/App/App.tsx, frontend/src/components/Breadcrumbs/Breadcrumbs.tsx, frontend/src/components/ConnectionStateIcon/ConnectionStateIcon.tsx, frontend/src/components/DeviceList/DeviceList.tsx, frontend/src/components/DeviceListItem/DeviceListItem.tsx, frontend/src/components/DeviceSetupItem/DeviceSetupItem.tsx, frontend/src/components/NewTarget/NewTarget.tsx, frontend/src/components/Router/Router.tsx, frontend/src/components/Router/index.ts, frontend/src/components/Scan/Scan.tsx, frontend/src/components/ScanNetwork/ScanNetwork.tsx, frontend/src/components/ServiceMiniState/ServiceMiniState.tsx, frontend/src/components/ServiceName/ServiceName.tsx, frontend/src/components/Target/Target.tsx, frontend/src/components/UninstallSetting/UninstallSetting.tsx, frontend/src/index.tsx, frontend/src/pages/NetworkPage/NetworkPage.tsx, frontend/src/pages/ServicesPage/ServicesPage.tsx, frontend/src/pages/SettingsPage/SettingsPage.tsx, frontend/src/pages/SetupServices/SetupServices.tsx, frontend/src/pages/SetupView/SetupView.tsx
Since your device appears in the device list, make it link to the device setup screen and keep it at the top of the list. If it's not setup link to setup.
1. Sign in
3. Click setup your device
4. Go back to the device list, and see it there and be able to get to the setup screen from it.
5. Test working with the device.
Think about removing the link in the setup page.
<https://remoteit.atlassian.net/browse/DESK-237>
=> [DESK-237] This device linked to hosted device setup

common/types.d.ts, frontend/src/components/DataDisplay/DataDisplay.tsx, frontend/src/components/DeviceList/DeviceList.tsx, frontend/src/components/DeviceListItem/DeviceListItem.tsx, frontend/src/components/Duration/Duration.tsx, frontend/src/components/SearchField/SearchField.tsx, frontend/src/helpers/mockData.ts, frontend/src/models/devices.ts, frontend/src/pages/ServicePage/ServicePage.tsx, frontend/src/pages/ServicesPage/ServicesPage.tsx, frontend/src/services/graphQL.ts, frontend/src/styling/theme.ts, frontend/src/types.d.ts
… graphql data query
Fixed missing "this device" data when device not part of query
updated graphql data query and display
1. Sign in to a system that is already registered
3. Click the filter button twice to filter our online devices
4. You should see the state of "this device" remain online
<https://remoteit.atlassian.net/browse/DESK-237>
=> [DESK-237] Fix local device data and update GraphQL queries

backend/package-lock.json, frontend/src/buttons/ResetButton/ResetButton.tsx, frontend/src/components/DataDisplay/DataDisplay.tsx, frontend/src/components/DeviceList/DeviceList.tsx, frontend/src/components/DeviceSetupItem/DeviceSetupItem.tsx, frontend/src/components/InlineSetting/InlineSetting.tsx, frontend/src/components/Router/Router.tsx, frontend/src/constants.ts, frontend/src/pages/SettingsPage/SettingsPage.tsx, frontend/src/services/applications.ts, frontend/src/styling/theme.ts, package-lock.json
Update graphql api url
Styling fixes
Device list cleanup and handling of duplicate 'this' device
Adding Samba launch type
Fix crashing when no last reported date
When signing in always default to device list
1. Sign in
2. Go to a device with smb
3. Try to launch it
4. You should see it launch with smb://
<https://remoteit.atlassian.net/browse/DESK-610>
<https://remoteit.atlassian.net/browse/DESK-590>
=> [DESK-590][DESK-610] Launch smb type and fix missing data bug

backend/src/Command.ts, frontend/src/models/auth.ts, frontend/src/models/devices.ts
Try and refresh the session token if it has expired on a device list refresh
Also small change to support new CLI scanning update
1. Sign in
2. Wait a... day or so?
3. Try and load the device list.
<https://remoteit.atlassian.net/browse/DESK-622>
=> [DESK-622] graphql expired refresh

backend/package-lock.json, backend/package.json, backend/src/sharedCopy/constants.ts, frontend/package-lock.json, frontend/package.json, frontend/src/components/DataDisplay/DataDisplay.tsx, frontend/src/components/NewTarget/NewTarget.tsx, frontend/src/services/graphQL.ts, frontend/src/shared/constants.ts, package-lock.json, package.json
Version bump 
GraphQL API based on version type
Tiny bug fix and wording fix
=> Version 2.6.1 bump

frontend/src/buttons/ConnectButton/ConnectButton.tsx, frontend/src/buttons/DisconnectButton/DisconnectButton.tsx, frontend/src/helpers/Analytics.ts, frontend/src/services/Controller.ts
Analytics update of connectionType
1. After this is released it will report into segment
<https://remoteit.atlassian.net/browse/DESK-617>
=> [DESK-617] update connectionType for analytics

backend/package-lock.json, backend/package.json, backend/src/Connection.ts, backend/src/ConnectionPool.ts, backend/src/cliStrings.ts, backend/src/constants.ts, frontend/package-lock.json, frontend/package.json, package-lock.json, package.json
Waiting for success to connect to service
Bug fixes
1. Sign in
2. Go to service
3. Click connect
4. You should see the spinner for a bit until successful
<https://remoteit.atlassian.net/browse/CLI-499>
=> [CLI-499] Wait for success to connect

backend/package-lock.json, backend/package.json, backend/src/Application.ts, backend/src/Command.ts, backend/src/ConnectionPool.ts, backend/src/Controller.ts, backend/src/cliStrings.ts, backend/src/constants.ts, frontend/package-lock.json, frontend/package.json, frontend/src/components/UninstallSetting/UninstallSetting.tsx, package-lock.json, package.json
Wait for credentials to start up. Also fix uninstaller and AuthHash cleaning from commands
This can be tested with a blank slate install on windows 10. There will be an error if not working correct when you first try to connect.
<https://remoteit.atlassian.net/browse/DESK-642>
=> [DESK-642] Wait for credentials to start up

backend/package-lock.json, backend/package.json, backend/src/CLI.ts, backend/src/Connection.ts, backend/src/cliStrings.ts, backend/src/constants.ts, frontend/package-lock.json, frontend/package.json, frontend/src/models/ui.ts, frontend/src/pages/Page/Page.tsx, frontend/src/pages/SettingsPage/SettingsPage.tsx, frontend/src/pages/SetupWaiting/SetupWaiting.tsx, package-lock.json, package.json
Includes CLI `v1.3.2`
* Uninstaller fixed
* App version added to feedback email
* Success snackbar instead of page
1. Sign in
2. General regression testing
<https://remoteit.atlassian.net/browse/DESK-532>
=> [DESK-532] CLI fixes

backend/src/sharedCopy/nameHelper.ts, frontend/src/components/Target/Target.tsx, frontend/src/pages/SetupDevice/SetupDevice.tsx, frontend/src/shared/nameHelper.ts
Validation of the device limit max and reuse the same validation
1. Sign in
2. Go to Add a device
3. Try to add characters nonalphanumeric or name more than 100 characters
4. You should see the validation
https://remoteit.atlassian.net/browse/DESK-397
=> [DESK-397] device name add validation

frontend/src/buttons/DeleteButton/DeleteButton.tsx, frontend/src/models/devices.ts
Leave device
1. Sign in
2. Go to Devices
3. Click one device share with me
4. You should see the icon trash
=> [DESK-649] Leave device

package.json, uninstaller.nsh
allow custom installation location on Windows
1. Install
2. Select the folder when you would like to install remoteit
3. You should see the folder remoteit into your previews selected folder
4. Uninstall
5. You shouldn't see the folder remoteit into your previews selected folder
https://remoteit.atlassian.net/browse/DESK-606
=> [DESK-606] allow custom installation location on Windows

frontend/src/buttons/LaunchButton/LaunchButton.tsx
a useEffect hook was added to update the username when the username is modified in the redux state.
1. Sign in
2. Go to...
3. Click...
=> [DESK-593] useEffect was added for updating the username

frontend/src/components/LocalhostScanForm/LocalhostScanForm.tsx, frontend/src/pages/SetupDevice/SetupDevice.tsx
Remove registration blocking while loading
1. Sign in to a device through a web browser 
2. Notice you can still register the device while the services are loading
<https://remoteit.atlassian.net/browse/DESK-652>
=> [DESK-652] Remove registration blocking while loading

backend/package-lock.json, backend/package.json, backend/src/CLI.ts, backend/src/Controller.ts, backend/src/Installer.ts, backend/src/constants.ts, backend/src/index.ts, frontend/package-lock.json, frontend/package.json, frontend/src/components/DeviceList/DeviceList.tsx, frontend/src/models/binaries.ts, frontend/src/pages/SettingsPage/SettingsPage.tsx, package-lock.json, package.json
CLI connected status hardening
DESK-650 Installer manual reinstall hardening
Improved logging of uncaught promise rejections
Ensure we display registered devices in the device list even if they … …
CLI v1.3.7
<https://remoteit.atlassian.net/browse/DESK-650>
=> [DESK-650] Cleanup

backend/src/server.ts, frontend/src/components/SettingsDisableNetworkItem/SettingsDisableNetworkItem.tsx, frontend/src/components/SettingsDisableNetworkItem/index.ts, frontend/src/components/SettingsListItem/SettingsListItem.tsx, frontend/src/pages/SettingsPage/SettingsPage.tsx, package-lock.json
A switch button was added in settings / advanced. It let the user to disable the local network discovery
1. Sign in
2. Go to...
3. Click...
<https://remoteit.atlassian.net/browse/DESK-647>
=> [DESK-647] user wants to disable the local network discovery 

uninstaller.nsh
Fix desktop uninstaller
1. Sign in
2. Go to...
3. Click...
https://remoteit.atlassian.net/browse/DESK-653
=> [Desk 653] desktop uninstaller

backend/src/User.ts, frontend/src/models/auth.ts, src/ElectronApp.ts
[DESK-376] Remove user.json from the backend
1. Sign in
2. Go to...
3. Click...
https://remoteit.atlassian.net/browse/DESK-376
[DESK-376]: https://remoteit.atlassian.net/browse/DESK-376
=> [DESK-376] Remove user.json from backend

uninstaller.nsh
[DESK-653] prompt to unregister device
1. Install desktop app
2. Login
3. Set up your device
4. Uninstall
4. You should see a prompt
https://remoteit.atlassian.net/browse/DESK-653
[DESK-653]: https://remoteit.atlassian.net/browse/DESK-653
=> [DESK-653] prompt to unregister device

frontend/src/components/SearchField/SearchField.tsx
I created a onKeyPress on an input to clean the input if the term on the input is blank or has 1 letter.
- [ x ] Pull Request title is in the format `[PROJ-12345] Some useful description here...`
- [ x ] The git branch is in the format `PROJ-12345-some-useful-description-here`
- [ x ] I have added one or more reviewers
- [ x ] This PR only contains one isolated change (bug fix, feature, etc)
- [ x ] I have manually reviewed this PR to make sure only the files I intended to change were changed and nothing else
- [ x ] I have notified reviewers on Slack by @ mentioning them in the `#desktop`channel
- [ x ] I have moved the Jira ticket into `Resolved` state and made a note in the ticket with a link to this PR
1. Sign in
2. Go to...
3. Click...
@matiaskochman …
=> [DESK-648] search display issue

backend/src/CLI.ts, backend/src/Controller.ts, backend/src/User.ts
Clear credentials was broken
1. Sign in to your device
2. Click clear credentials
3. Check that the cli config file has removed the username and authhash
4. Log back in and be prompted for admin password to sign back into cli
<https://remoteit.atlassian.net/browse/DESK-665>
=> [DESK-665] clear credentials

frontend/src/helpers/connectionHelper.ts, frontend/src/models/devices.ts
search all de devices to delete connections that are not linked anymore because of deleted devices.
- [  x ] Pull Request title is in the format `[PROJ-12345] Some useful description here...`
- [ x ] I have added one or more reviewers
- [ x ] This PR only contains one isolated change (bug fix, feature, etc)
- [ x ] I have manually reviewed this PR to make sure only the files I intended to change were changed and nothing else
- [ x ] I have notified reviewers on Slack by @ mentioning them in the `#desktop`channel
- [ x ] I have moved the Jira ticket into `Resolved` state and made a note in the ticket with a link to this PR
1. Sign in
2. Go to...
3. Click...
=> [DESK-661]

frontend/src/components/InstallationNotice/InstallationNotice.tsx, frontend/src/components/LocalhostScanForm/LocalhostScanForm.tsx
[DESK-0000] fix blank error
1. Install Desk app
2. Install CLI
3. Sometime after the installation shows an error `{}`, this pr check if the error has descriptions or any in the object
Task
https://remoteit.atlassian.net/browse/DESK-679
=> [DESK-0000] fix blank error

backend/src/Connection.ts, backend/src/ConnectionPool.ts, backend/src/cliStrings.ts, frontend/src/services/Controller.ts
Make connections more responsive by not awaiting cli response
Force connect on button press for enabled=true retry=false case
<https://remoteit.atlassian.net/browse/DESK-663>
<https://remoteit.atlassian.net/browse/DESK-678>
=> [DESK-663][DESK-678] connection responsive

backend/package-lock.json, backend/package.json, backend/src/constants.ts, backend/src/sharedCopy/applications.ts, frontend/package-lock.json, frontend/package.json, frontend/src/buttons/LaunchButton/LaunchButton.tsx, frontend/src/components/NameSetting/NameSetting.tsx, frontend/src/components/UsernameSetting/UsernameSetting.tsx, frontend/src/pages/SettingsPage/SettingsPage.tsx, frontend/src/pages/UsersPage/UsersPage.tsx, frontend/src/shared/applications.ts, package-lock.json, package.json, src/TrayMenu.ts
- CLI v1.5.1
- DESK-685 ensure launch copy string has protocol
- Windows system tray not showing connections
- Update page tracking name for users page
- Protect connection names from entering special characters
- Launch button do not modify connection
- Updated quit button language
<https://remoteit.atlassian.net/browse/DESK-685>
=> [DESK-685] launch copy string and updates

frontend/src/helpers/Analytics.ts
1. Sign in
2. Go to...
3. Click...
https://remoteit.atlassian.net/browse/DESK-617
=> [DESK-617] Fix connection type peer

backend/package-lock.json, backend/package.json, backend/src/CLI.ts, backend/src/server.ts, frontend/package-lock.json, frontend/package.json, frontend/src/components/DeviceListEmpty/DeviceListEmpty.tsx, package-lock.json, package.json, uninstaller.nsh
Always sign in
Fix search no results message
1. Pre install CLI
2. Sign in without install prompt
3. Desktop should still sign into CLI and start it's services
<https://remoteit.atlassian.net/browse/DESK-690>
<https://remoteit.atlassian.net/browse/DESK-648>
=> [DESK-690][DESK-648] signin always

src/ElectronApp.ts, src/TrayMenu.ts
Connection pool update checks for system tray
1. Sign in
2. Close the main remoteit window
3. Click on a recent connection to connect
4. You should see the connection come online in the tray menu after a couple seconds
<https://remoteit.atlassian.net/browse/DESK-691>
=> [DESK-691] Connection pool update checks for system tray

backend/src/Installer.ts, backend/src/constants.ts
Just updating download url for production release.
=> Update to production download url

backend/src/CLI.ts, backend/src/Controller.ts, backend/src/Installer.ts, backend/src/User.ts, backend/src/server.ts, frontend/src/pages/SetupDevice/SetupDevice.tsx
Fix cli signin to be more aware of installation status
1. clear credentials in desktop
2. run sudo remoteit uninstall 
3. sign into desktop
4. You should not see a prompt to sign in on the install cli screen
<https://remoteit.atlassian.net/browse/DESK-693>
=> [DESK-693] CLI signin install overlap

backend/src/CLI.ts, backend/src/ConnectionPool.ts, backend/src/Installer.ts, backend/src/constants.ts, backend/src/index.ts, frontend/src/components/InstallationNotice/InstallationNotice.tsx
Handle missing file download errors.
Also update install screen to remove indication of sudo, since users will not now be prompted.
<https://remoteit.atlassian.net/browse/DESK-694>
=> [DESK-694] Download hardening

backend/src/Installer.ts, backend/src/environment.ts, package.json
Support for windows 32 bit installation
1. Get 32 bit windows machine
2. Install
3. It should run and install the correct 32 bit CLI
<https://remoteit.atlassian.net/browse/DESK-697>
=> [DESK-697] Support for windows 32 bit installation

uninstaller.nsh
[DESK-359] Install CLI in the windows installation and hide terminal 
[DESK-359] Install CLI in the windows installation and hide terminal 
1. Install in windows environtment.
2. you should see the CLI installed in the same process
https://remoteit.atlassian.net/browse/DESK-359
[DESK-359]: https://remoteit.atlassian.net/browse/DESK-359
[DESK-359]: https://remoteit.atlassian.net/browse/DESK-359
=> [DESK-359] Install CLI in the windows installation and hide terminal

backend/src/CLI.ts, backend/src/User.ts, installer.nsh, package-lock.json, package.json
Updates based on testing installation and updates on windows
1. Install new installer without deregistering your device
2. Check that connections / registration work
3. Remove cli and sign out
4. Install and check everything works
<https://remoteit.atlassian.net/browse/DESK-359>
=> [DESK-359] win installer update

frontend/src/buttons/AddUserButton/AddUserButton.tsx, frontend/src/components/ListItemCheckbox/ListItemCheckbox.tsx, frontend/src/components/ServiceName/ServiceName.tsx, frontend/src/components/SharedUsersHeader/SharedUsersHeader.test.tsx, frontend/src/components/SharedUsersHeader/SharedUsersHeader.tsx, frontend/src/components/SharedUsersList/SharedUsersList.tsx, frontend/src/components/Title/Title.tsx, frontend/src/pages/ServicePage/ServicePage.tsx, frontend/src/pages/ServicesPage/ServicesPage.tsx, frontend/src/pages/UsersPageDevice/UsersPageDevice.tsx, frontend/src/pages/UsersPageService/UsersPageService.tsx
@mauricio0000 
Trying something new by adding explanations to my PR in the hopes that we can learn from each other. 
Let me know if you find this useful to not.
Thanks!
https://remoteit.atlassian.net/browse/DESK-717
=> [DESK-717] Fixing checkbox clicks and add sharing visibility

frontend/src/buttons/ComboButton/ComboButton.tsx, frontend/src/buttons/ComboButton/index.ts, frontend/src/buttons/LaunchButton/LaunchButton.tsx, frontend/src/components/Body/Body.tsx, frontend/src/components/Container/Container.tsx, frontend/src/components/DeviceList/DeviceList.tsx, frontend/src/components/DeviceListItem/DeviceListItem.tsx, frontend/src/components/DeviceShareContainer/DeviceShareAdd.tsx, frontend/src/components/DeviceShareContainer/DeviceShareContainer.tsx, frontend/src/components/DeviceShareContainer/SharingForm.tsx, frontend/src/components/ListItemLocation/ListItemLocation.tsx, frontend/src/components/SearchField/SearchField.tsx, frontend/src/components/ServiceContextualMenu/ServiceContextualMenu.tsx, frontend/src/components/ServiceContextualMenu/index.ts, frontend/src/components/ServiceListItem/ServiceListItem.tsx, frontend/src/components/ServiceMiniState/ServiceMiniState.tsx, frontend/src/components/ServiceName/ServiceName.tsx, frontend/src/components/SessionsTooltip/SessionsTooltip.tsx, frontend/src/components/TargetPlatform/TargetPlatform.tsx, frontend/src/pages/LogPage/LogPage.tsx, frontend/src/pages/SharePage/SharePage.tsx, frontend/src/pages/UsersPageDevice/UsersPageDevice.tsx, frontend/src/pages/UsersPageService/UsersPageService.tsx, frontend/src/styling/index.ts, frontend/src/styling/theme.ts, frontend/src/types.d.ts
Provide service context menus on device list.
Show scroll bars on hover.
Copy deep link from menu.
Other UI improvements.
1. Sign in
3. Click a service indicator
4. You should see a new menu
5. You should be able to copy a deep link
<https://remoteit.atlassian.net/browse/DESK-723>
=> [DESK-723] context menu

package.json, pkg-scripts/preinstall
1. Sign in
2. Go to...
3. Click...
=> [DESK-718] add logs of the version on the mac installation

pkg-scripts/postinstall
Fix installation version
1. Sign in
2. Go to...
3. Click...
https://remoteit.atlassian.net/browse/DESK-728
=> [DESK-728] mac cli version

backend/src/Controller.ts
Read config on signin.
1. Delete the device
2. Sign out
3. Register a device with cli
4. Sign in through a browser http://localhost:29999
5. You should land on the setup page with the device already there
<https://remoteit.atlassian.net/browse/DESK-735>
=> [DESK-735] Read config on sign in

backend/src/Controller.ts, frontend/src/components/ServiceName/ServiceName.tsx, frontend/src/components/Sidebar/Sidebar.tsx, frontend/src/components/TargetPlatform/TargetPlatform.tsx, frontend/src/styling/index.ts
Add platform logo to sidebar
1. Sign in through a browser
2. See the platform icon displayed top left
3. Connect to an aws device's admin panel
4. See the aws logo in top left
<https://remoteit.atlassian.net/browse/DESK-731>
=> [DESK-731] add platform logo to sidebar

installer.nsh
[DESK-729] Add logs to installation and uninstallation windows env
1. Sign in
2. Go to...
3. Click...
https://remoteit.atlassian.net/browse/DESK-729
[DESK-729]: https://remoteit.atlassian.net/browse/DESK-729
=> [DESK-729] Add logs to installation and uninstallation windows env

frontend/src/buttons/AddFromNetworkButton/AddFromNetworkButton.tsx, frontend/src/buttons/AddFromNetworkButton/index.ts, frontend/src/buttons/AddServiceButton/AddServiceButton.tsx, frontend/src/components/DeviceShareContainer/ContactCardActions.tsx, frontend/src/components/Router/Router.tsx, frontend/src/components/ScanNetwork/ScanNetwork.tsx, frontend/src/components/ServiceForm/ServiceForm.tsx, frontend/src/components/Targets/Targets.tsx, frontend/src/pages/DeviceEditPage/DeviceEditPage.tsx, frontend/src/pages/ServiceAddPage/ServiceAddPage.tsx, frontend/src/pages/ServiceEditPage/ServiceEditPage.tsx
Need the network scan feature from the device edit page next to the add service.
1. Sign in
2. Go to this device's edit page
3. Click the scan network icon in the service section
4. You should see the network page 
5. Click a result and the add button
6. You should go to the add service page with the form filled out
<https://remoteit.atlassian.net/browse/DESK-738>
=> [DESK-738] scan from device edit

frontend/src/components/DeviceShareContainer/ContactCard.tsx, frontend/src/components/DeviceShareContainer/ContactCardActions.tsx, frontend/src/components/DeviceShareContainer/DeviceShareAdd.tsx, frontend/src/components/DeviceShareContainer/DeviceShareContainer.tsx, frontend/src/components/DeviceShareContainer/DeviceShareDetails.tsx, frontend/src/components/DeviceShareContainer/SharingForm.tsx, frontend/src/components/SharedUsersList/SharedUsersList.tsx, frontend/src/components/UsersSelect/UsersSelect.tsx, frontend/src/models/contacts.ts, frontend/src/models/shares.ts, frontend/src/types.d.ts
[DESK-736] refactors and fixing
1. Sign in
2. Go to...
3. Click...
https://remoteit.atlassian.net/browse/DESK-736
[DESK-736]: https://remoteit.atlassian.net/browse/DESK-736
=> [DESK-736] refactors and fixing

frontend/src/services/graphQL.ts
Remove the name field from graphQL device list query if empty
<https://remoteit.atlassian.net/browse/[DESK-742]>
[DESK-742]: https://remoteit.atlassian.net/browse/DESK-742
=> [DESK-742] device list no name

installer.nsh
[DESK-713] uninstall show confirm remove only when the device  was set
1. Sign in
2. Go to...
3. Click...
https://remoteit.atlassian.net/browse/DESK-713
[DESK-713]: https://remoteit.atlassian.net/browse/DESK-713
=> [DESK-713] uninstall show confirm remove only when the device  was set

package.json
https://remoteit.atlassian.net/browse/DESK-739
come back to DMG
1. Sign in
2. Go to...
3. Click...
https://remoteit.atlassian.net/browse/DESK-739
=> DESK-739-mac-update-installer

backend/src/sharedCopy/constants.ts, frontend/src/buttons/AddUserButton/AddUserButton.tsx, frontend/src/components/Avatar/Avatar.tsx, frontend/src/components/Breadcrumbs/Breadcrumbs.tsx, frontend/src/components/DeviceListEmpty/DeviceListEmpty.tsx, frontend/src/components/DeviceSetupItem/DeviceSetupItem.tsx, frontend/src/components/DeviceShareContainer/DeviceShareContainer.tsx, frontend/src/components/DeviceShareContainer/DeviceShareDetails.tsx, frontend/src/components/InlineSetting/InlineSetting.tsx, frontend/src/components/NetworkScanLocation/NetworkScanLocation.tsx, frontend/src/components/Router/Router.tsx, frontend/src/components/ServiceContextualMenu/ServiceContextualMenu.tsx, frontend/src/components/ServiceListItem/ServiceListItem.tsx, frontend/src/components/ServiceName/ServiceName.tsx, frontend/src/components/ShareDetails/ShareDetails.tsx, frontend/src/models/backend.ts, frontend/src/models/devices.ts, frontend/src/pages/DeviceEditPage/DeviceEditPage.tsx, frontend/src/pages/ServiceEditPage/ServiceEditPage.tsx, frontend/src/pages/ServicePage/ServicePage.tsx, frontend/src/pages/SettingsPage/SettingsPage.tsx, frontend/src/pages/SetupDevice/SetupDevice.tsx, frontend/src/pages/SetupWaiting/SetupWaiting.tsx, frontend/src/pages/SharePage/SharePage.tsx, frontend/src/pages/UnauthorizedPage/UnauthorizedPage.tsx, frontend/src/pages/UnauthorizedPage/index.ts, frontend/src/shared/constants.ts
Allow api configs to be overriden
Display unauthorized message if deep linked to a service
Clear connection button
Routing path fixes
Avatar display email update
Service update and registration bugs
Service display enhancements
DESK-709 rename clear credentials to sign out command
DESK-744 remove network down error message
<https://remoteit.atlassian.net/browse/DESK-706>
<https://remoteit.atlassian.net/browse/DESK-709>
<https://remoteit.atlassian.net/browse/DESK-744>
=> [DESK-706][DESK-709][DESK-744] Routing and bug fixes

installer.nsh
1. Update a new realease and you should not see any message of uninstall
https://remoteit.atlassian.net/browse/DESK-749
=> [DESK-749] custom update

frontend/src/components/SharedUsersList/SharedUsersList.tsx
[DESK-711] add fragment with key prop
1. Sign in
2. Go to...
3. Click...
https://remoteit.atlassian.net/browse/DESK-711
[DESK-711]: https://remoteit.atlassian.net/browse/DESK-711
=> [DESK-711] add fragment with key prop

common/types.d.ts, frontend/src/buttons/ForgetButton/ForgetButton.tsx, frontend/src/buttons/RefreshButton/RefreshButton.tsx, frontend/src/components/ConnectionsList/ConnectionsList.tsx, frontend/src/components/Router/Router.tsx, frontend/src/components/ServiceMiniState/ServiceMiniState.tsx, frontend/src/components/ServiceName/ServiceName.tsx, frontend/src/components/SessionsList/SessionsList.tsx, frontend/src/components/SessionsList/index.ts, frontend/src/components/Title/Title.tsx, frontend/src/models/devices.ts, frontend/src/pages/ConnectionsPage/ConnectionsPage.tsx, frontend/src/pages/DevicesPage/DevicesPage.tsx, src/ElectronApp.ts
Display connections by other users on the connections page
1. Sign in
2. Go to connections tab
3. You should see any shared users that are connected listed below your connections at the bottom
<https://remoteit.atlassian.net/browse/DESK-710>
=> [DESK-710] show shared connections

frontend/src/services/graphQLDevice.ts
=> GraphQL update from Benoit

frontend/src/components/SharedUsersList/SharedUsersList.tsx, frontend/src/components/UserListItem/UserListItem.tsx, frontend/src/components/UserListItem/index.ts
refactors shared user list and fix sort
split the list of the user connected and not connected.
create a component to user Row Item
hide details of services by usert in the service page
1. Sign in
2. Go to Device
3. Click User Shared
4. You should see  sort the users by connected 
none
=> [DESK-0000] refactors share user and fix sort

installer.nsh
[DESK-756] validate file remoteit.exe CLI before to run NSIS
1. Sign in
2. Go to...
3. Click...
https://remoteit.atlassian.net/browse/DESK-756
[DESK-756]: https://remoteit.atlassian.net/browse/DESK-756
=> [DESK-756] validate file remoteit.exe CLI before to run NSIS

frontend/src/components/Sidebar/Sidebar.tsx, frontend/src/pages/Page/Page.tsx, frontend/src/styling/theme.ts
On small screen remove the frame and side bar so that you can access the interface.
1. Sign in to the admin panel on a mobile device
2. Side bar and border should not appear
<https://remoteit.atlassian.net/browse/DESK-745>
=> [DESK-745] remove border mobile

installer.nsh
fix upgrade installation nsis
1. Have installed a previus version desktop - CLI
2. Install a new version with a newer version CLI
3. You should see installed the newer version desktop and CLI
https://remoteit.atlassian.net/browse/DESK-756
=> [DESK-756] fix upgrade installation nsis

frontend/src/components/Router/Router.tsx, frontend/src/pages/SetupDevice/SetupDevice.tsx
1. Sign in
2. Register a device
3. See the waiting screen
4. Land on the edit page
<https://remoteit.atlassian.net/browse/DESK-773>
=> [DESK-773] Registration workflow

frontend/src/models/auth.ts, frontend/src/services/Controller.ts
1. Sign in with user 1 
2. Sign out
3. Signin with user 2
4. You should see and error message saying user 1 is signed in
<https://remoteit.atlassian.net/browse/DESK-780>
=> [DESK-780] sign in lockout

frontend/src/models/shares.ts
[DESK-0000]fix fetch device-after delete user
=> [DESK-0000]fix fetch device-after delete user

installer.nsh
[DESK-778] fix update fail
https://remoteit.atlassian.net/browse/DESK-778
[DESK-778]: https://remoteit.atlassian.net/browse/DESK-778
=> [DESK-778] fix update fail

frontend/src/components/ServiceForm/ServiceForm.tsx, frontend/src/models/devices.ts, frontend/src/models/ui.ts, frontend/src/pages/AccountSharePage.tsx, frontend/src/services/platformConfiguration.ts
1. Sign in to AWS AMI
2. Go to edit / create a service
3. The routing dropdown should be fixed to p2p only with a message displayed to the right
<https://remoteit.atlassian.net/browse/DESK-775>
=> [DESK-775] Force p2p routing

frontend/src/pages/DeviceLogPage/EventIcon.tsx, frontend/src/pages/DeviceLogPage/EventMessage.tsx
[DESK-783] fix icon wron logs
https://remoteit.atlassian.net/browse/DESK-783
[DESK-783]: https://remoteit.atlassian.net/browse/DESK-783
=> [DESK-783] fix icon wron logs

frontend/src/models/auth.ts
fix google signout
Use google sigin-in and then logout.  Try to use google signin again.  Should be prompted to select account (if multiple accounts)
<https://remoteit.atlassian.net/browse/DESK-791>
=> [Desk-791] fix google signout

backend/src/Controller.ts, backend/src/sharedCopy/applications.ts, frontend/src/components/PortSetting/PortSetting.tsx, frontend/src/pages/SignInPage/SignInPage.tsx, frontend/src/shared/applications.ts
Fix null string showing up in Launch URL
1. Sign in
2. Go to a service detail page
3. You should see the port set
<https://remoteit.atlassian.net/browse/DESK-804>
=> DESK-804 Fix missing freeport data on initial load

frontend/src/models/devices.ts
Fix parsing of total in device query result
1. Sign in
2. Go to device list with more than 50 devices
3. You should see the load more as well as the total count in the search bar.
<https://remoteit.atlassian.net/browse/DESK-810>
=> DESK-810 no total count

backend/src/User.ts, backend/src/server.ts, common/types.d.ts, frontend/src/components/AccountSelect.tsx, frontend/src/hooks/usePermissions.ts, frontend/src/models/auth.ts, frontend/src/pages/DeviceLogPage/DeviceLogPage.tsx
Get authHash from graphQL and sign into backend with yoicsId
1. Sign in with a user account that has a YoicsId (legacy username)
4. You should be able to make a peer to peer connection
<https://remoteit.atlassian.net/browse/DESK-808>
=> DESK-808 Username sign in

backend/package-lock.json, backend/package.json, frontend/package-lock.json, frontend/package.json, frontend/src/pages/DeviceEditPage/DeviceEditPage.tsx, package-lock.json, package.json
Adding refresh button to device edit page
1. Sign in
2. Go to a device
3. Click the pencil
4. You should see the refresh icon top right
<https://remoteit.atlassian.net/browse/DESK-812>
=> DESK-812 refresh remote ui

frontend/src/buttons/ConnectButton/ConnectButton.tsx
Fetch single device when device disconnects
1. Sign in
2. Go to a device and connect
3. Click disconnect
4. You should see the device refresh it's data
<https://remoteit.atlassian.net/browse/DESK-746>
=> DESK-746 Fetch single device when device disconnects

.gitignore, backend/src/Connection.ts, common/types.d.ts, frontend/src/buttons/ClearButton/ClearButton.tsx, frontend/src/buttons/ConnectButton/ConnectButton.tsx, frontend/src/buttons/DynamicButton/DynamicButton.tsx, frontend/src/components/LicensingNotice.tsx, frontend/src/components/LicensingSetting.tsx, frontend/src/components/ServiceListItem/ServiceListItem.tsx, frontend/src/components/ServiceMiniState/ServiceMiniState.tsx, frontend/src/components/ServiceName/ServiceName.tsx, frontend/src/helpers/mockData.ts, frontend/src/models/licensing.ts, frontend/src/pages/ServicePage/ServicePage.tsx, frontend/src/pages/ServicesPage/ServicesPage.tsx, frontend/src/services/graphQL.ts, frontend/src/services/graphQLDevice.ts, frontend/src/styling/index.ts, frontend/src/styling/theme.ts
Added indications of licensing on services in the the settings page
1. Sign in
2. Go to and aws device
3. You should see if a service is in an evaluation period or unlicensed
_* This is a difficult situation to simulate - might need @penngrove assistance to test_
<https://remoteit.atlassian.net/browse/DESK-799>
=> DESK-799 aws service limits

common/types.d.ts, frontend/package-lock.json, frontend/package.json, frontend/src/components/Breadcrumbs/Breadcrumbs.tsx, frontend/src/components/LicensingSetting.tsx, frontend/src/components/ServiceForm/ServiceForm.tsx, frontend/src/helpers/connectionHelper.ts, frontend/src/models/accounts.ts, frontend/src/models/backend.ts, frontend/src/models/devices.ts, frontend/src/pages/ConnectionsPage/ConnectionsPage.tsx, frontend/src/pages/LogPage/LogPage.tsx, frontend/src/pages/ServiceEditPage/ServiceEditPage.tsx, frontend/src/pages/ServicePage/ServicePage.tsx, frontend/src/services/graphQLDevice.ts, frontend/src/store.tsx
Fixed device list selection errors when another user's device list is active and you edit the local device configuration.
1. Sign in
2. Select another accounts device list
3. Go to the settings page and click to configure the local device
4. You should be able to add/remove services and change all config options as normal
<https://remoteit.atlassian.net/browse/DESK-819>
=> DESK-819 service in both accounts

frontend/src/buttons/DeleteButton/DeleteButton.tsx
Don't allow leaving of a device from a shared device list
1. Sign in
2. Go to another device list
3. Click on a device and then edit the device
4. You should not see a trash can icon at the top
<https://remoteit.atlassian.net/browse/DESK-815>
=> DESK-815 shared list delete

common/types.d.ts, frontend/src/buttons/FilterButton/FilterButton.tsx, frontend/src/components/App/App.tsx, frontend/src/components/DeviceList/DeviceList.tsx, frontend/src/components/FilterDrawerContent/FilterDrawerContent.tsx, frontend/src/components/FilterDrawerContent/FilterSelector.tsx, frontend/src/components/FilterDrawerContent/index.ts, frontend/src/models/devices.ts, frontend/src/pages/DevicesPage/DevicesPage.tsx, frontend/src/services/graphQLDevice.ts
Add feature sort and filter
1. Sign in
3. You should see the new section of filters and sort
https://remoteit.atlassian.net/browse/DESK-756
=> [DESK-704]filter and sort

backend/src/sharedCopy/applications.ts, common/types.d.ts, frontend/src/components/Confirm.tsx, frontend/src/components/InlineTextFieldSetting/InlineTextFieldSetting.tsx, frontend/src/components/LaunchSetting/index.ts, frontend/src/components/TemplateSetting/TemplateSetting.tsx, frontend/src/components/TemplateSetting/index.ts, frontend/src/models/accounts.ts, frontend/src/models/backend.ts, frontend/src/models/devices.ts, frontend/src/pages/ServicePage/ServicePage.tsx, frontend/src/shared/applications.ts, frontend/src/styling/theme.ts
Making copy templates editable
1. Sign in
2. Go to a service
3. Click to edit the copy command
4. You should see the edited copy command if you connect and click the copy icon
<https://remoteit.atlassian.net/browse/DESK-829>
=> DESK-829 edit copy command

frontend/src/buttons/ConnectButton/ConnectButton.tsx, frontend/src/buttons/FilterButton/FilterButton.tsx, frontend/src/components/App/App.tsx, frontend/src/components/Container/Container.tsx, frontend/src/components/DeviceList/DeviceList.tsx, frontend/src/components/DeviceListItem/DeviceListItem.tsx, frontend/src/components/FilterDrawerContent/FilterDrawerContent.tsx, frontend/src/components/FilterDrawerContent/FilterSelector.tsx, frontend/src/components/LicensingNotice.tsx, frontend/src/components/LicensingServiceNotice.tsx, frontend/src/models/accounts.ts, frontend/src/models/devices.ts, frontend/src/models/licensing.ts, frontend/src/models/ui.ts, frontend/src/pages/DevicesPage/DevicesPage.tsx, frontend/src/pages/ServiceAddPage/ServiceAddPage.tsx, frontend/src/pages/ServicePage/ServicePage.tsx, frontend/src/services/graphQLDevice.ts, frontend/src/styling/index.ts, frontend/src/styling/theme.ts
Adding license notice indicator to the settings footer icon
1. Sign in to an account with a license notice on the settings page
2. You should see a blue dot indicator on the settings icon in the footer
<https://remoteit.atlassian.net/browse/DESK-826>
=> DESK-826 license indicator

backend/package-lock.json, backend/package.json, frontend/package-lock.json, frontend/package.json, frontend/src/components/InlineSetting/InlineSetting.tsx, package-lock.json, package.json
Fixed inline text field padding
Bump and tag version for alpha release.
=> Textfield padding

backend/src/CLI.ts, frontend/src/components/FilterDrawerContent/FilterSelector.tsx, frontend/src/components/ServiceName/ServiceName.tsx, frontend/src/models/accounts.ts, frontend/src/models/devices.ts, frontend/src/pages/Page/Page.tsx, frontend/src/services/graphQL.ts
Check signin before all commands
Error messaging cleanup
Fix device sorting with merged devices
1. Uninstall command line tools
2. Restart and Sign in
3. Install the service
4. Go to a device and try to connect
5. You should connect
<https://remoteit.atlassian.net/browse/DESK-835>
=> DESK-835 ensure signin

frontend/src/components/ServiceForm/ServiceForm.tsx, frontend/src/pages/DeviceLogPage/EventMessage.tsx, frontend/src/services/graphQLDevice.ts
Add hostname example to add / edit service form
<https://remoteit.atlassian.net/browse/DESK-839>
=> DESK-839 example hostname

backend/package-lock.json, backend/package.json, backend/src/Binary.test.ts, backend/src/Binary.ts, backend/src/CLI.ts, backend/src/binaryInstaller.test.ts, backend/src/binaryInstaller.ts, backend/src/constants.ts, backend/src/environment.ts, frontend/package-lock.json, frontend/package.json, frontend/src/components/LimitSetting.tsx, frontend/src/components/ServiceForm/ServiceForm.tsx, frontend/src/components/TemplateSetting.tsx, frontend/src/pages/DeviceLogPage/EventMessage.tsx, frontend/src/services/graphQLDevice.ts, frontend/src/services/graphQLMutation.ts, package-lock.json, package.json
DESK-857 move uninstall commands to sudo prompt
DESK-839 Update example hostname
Headless cli command update
Fix license display bug on settings page
Update saving of device and service attributes to GraphQL namespace
Service add / edit form multi line inputs for large values
<https://remoteit.atlassian.net/browse/DESK-857>
<https://remoteit.atlassian.net/browse/DESK-839>
=> DESK-839 DESK-857 example hostname

common/types.d.ts, frontend/src/components/ConnectionStateIcon/ConnectionStateIcon.tsx, frontend/src/components/DataDisplay/DataDisplay.tsx, frontend/src/components/DeviceListItem/DeviceListItem.tsx, frontend/src/components/Formats.tsx, frontend/src/components/QualityDetails.tsx, frontend/src/components/Quote.tsx, frontend/src/pages/DeviceDetailPage/DeviceDetailPage.tsx, frontend/src/pages/LanSharePage/LanSharePage.tsx, frontend/src/pages/ServicesPage/ServicesPage.tsx, frontend/src/services/graphQLDevice.ts
Provide connection quality issue indicator and more detailed connection info.
1. Sign in
2. Go to the device list
3. Click the icon of a device with a red / orange indicator on it
4. You should see the device list with an indication of connection quality
<https://remoteit.atlassian.net/browse/DESK-135>
=> DESK-135 connection quality

backend/src/CLI.ts, backend/src/Controller.ts, backend/src/binaryInstaller.test.ts, backend/src/binaryInstaller.ts, backend/src/cli-version.json, backend/src/cliStrings.ts
Fixing linux uninstall issues.
=> Uninstall linux

backend/src/User.ts, frontend/src/components/LicensingNotice.tsx, frontend/src/components/ServiceForm/ServiceForm.tsx, frontend/src/components/ServiceListItem/ServiceListItem.tsx, frontend/src/pages/DeviceEditPage/DeviceEditPage.tsx
Provide a notice that you can configure your device remotely via the admin panel.
1. Sign in
2. Go to a device with an admin panel that isn't "this device"
3. Click the edit device link
4. You should see a connect button to connect to the admin panel with a message 
<https://remoteit.atlassian.net/browse/DESK-776>
=> DESK-776 admin panel notice

backend/package-lock.json, frontend/package-lock.json, frontend/package.json, frontend/src/models/accounts.ts, frontend/src/models/applicationTypes.ts, frontend/src/models/auth.ts, frontend/src/models/backend.ts, frontend/src/models/binaries.ts, frontend/src/models/devices.ts, frontend/src/models/labels.ts, frontend/src/models/licensing.ts, frontend/src/models/logs.ts, frontend/src/models/rootModel.ts, frontend/src/models/shares.ts, frontend/src/models/ui.ts, frontend/src/services/Controller.ts, frontend/src/services/graphQLLogs.ts, frontend/src/store.tsx, package-lock.json
[DESK-789] rematch types 
1. Sign in
2. Go to...
3. Click...
https://remoteit.atlassian.net/browse/DESK-789
https://remoteit.atlassian.net/browse/DESK-827
[DESK-789]: https://remoteit.atlassian.net/browse/DESK-789
=> [DESK-789] rematch types

backend/src/ConnectionPool.ts
fixing shared devices state updating
1. Sign in
2. Go to a shared device list
3. Click connect 
4. You should see it connect
<https://remoteit.atlassian.net/browse/DESK-873>
=> DESK-873 shared devicelist connections

backend/package-lock.json, backend/package.json, backend/src/CLI.ts, backend/src/binaryInstaller.ts, backend/src/cli-version.json, frontend/package-lock.json, frontend/package.json, frontend/src/components/SessionsList/SessionsList.tsx, frontend/src/helpers/connectionHelper.ts, package-lock.json, package.json
Fixes duplicated connections on connections page
CLI v1.6.23
<https://remoteit.atlassian.net/browse/DESK-873>
=> DESK-873 shared device list fixes

installer.nsh
https://remoteit.atlassian.net/browse/DESK-876
=> [DESK-876] windows uninstaller config

frontend/package-lock.json, frontend/package.json
update dependency remath immer to 2.0
=> update dependency remath immer to 2.0

installer.nsh
=> fix nsis unregister

backend/package-lock.json, backend/package.json, frontend/package-lock.json, frontend/package.json, package-lock.json, package.json
Update electron packages to latest to support Big Sur
<https://remoteit.atlassian.net/browse/DESK-881>
=> DESK-881 Update electron

backend/src/binaryInstaller.ts
Symlink to absolute file paths instead of directory
<https://remoteit.atlassian.net/browse/DESK-883>
=> DESK-883 safe symlinks

frontend/src/components/SignInForm/SignInForm.tsx
[DESK-853] hide captcha
[DESK-853]: https://remoteit.atlassian.net/browse/DESK-853
=> [DESK-853] hide captcha

backend/src/CLI.ts, backend/src/Controller.ts, backend/src/cli-version.json, backend/src/cliStrings.ts, common/types.d.ts, frontend/src/buttons/RestoreButton.tsx, frontend/src/components/Confirm.tsx, frontend/src/components/DeviceList/DeviceList.tsx, frontend/src/components/DeviceListItem/DeviceListItem.tsx, frontend/src/components/DeviceSetupItem/DeviceSetupItem.tsx, frontend/src/components/Notice.tsx, frontend/src/components/ServiceName/ServiceName.tsx, frontend/src/models/backend.ts, frontend/src/models/devices.ts, frontend/src/models/ui.ts
Added ability to restore a device config from the cloud
1. Setup a Mac with a registered device
2. Open a terminal
3. `sudo remoteit agent stop`
4. `sudo rm /etc/remoteit/config.json`
5. `sudo remoteit agent start`
6. Open the app
7. Click the "Restore Device" link at the top of the device list
8. Select a device to restore
9. Click ok
10. Device should now be back
<https://remoteit.atlassian.net/browse/DESK-898>
=> DESK-898 device restoration

installer.nsh
Update of windows NSIS install script to address uninstall issues outlined here:
https://remoteit.atlassian.net/wiki/spaces/~662964166/pages/edit-v2/851902493
See testing section of this document:
https://remoteit.atlassian.net/wiki/spaces/~662964166/pages/edit-v2/851902493
<https://remoteit.atlassian.net/browse/DESK-899>
=> DESK-899 pre install

frontend/src/components/DeviceSetupItem/DeviceSetupItem.tsx
DESK-900 Fix showing restore when not available and changing page to devices when clicked
<https://remoteit.atlassian.net/browse/DESK-900>
<https://remoteit.atlassian.net/browse/DESK-901>
=> DESK-900 DESK-901 Fix showing restore when not available and changing page to devices when clicked

backend/package-lock.json, backend/package.json, backend/src/cli-version.json, backend/src/sharedCopy/applications.ts, backend/src/sharedCopy/nameHelper.ts, frontend/package-lock.json, frontend/package.json, frontend/src/models/devices.ts, frontend/src/services/graphQLDevice.ts, frontend/src/shared/applications.ts, frontend/src/shared/nameHelper.ts, package-lock.json, package.json
- Default smb connections to localhost instead of 127.0.0.1
- CLI update
- version 2.9.5
<https://remoteit.atlassian.net/browse/DESK-905>
=> DESK-905 smb localhost

backend/src/environment.ts
Cast manufacturer platform code to number
<https://remoteit.atlassian.net/browse/RIRN-37>
=> RIRN-37 Cast manufacturer platform code to number

backend/src/Controller.ts, backend/src/launch.ts, backend/src/sharedCopy/applications.ts, common/types.d.ts, frontend/src/buttons/LaunchButton/LaunchButton.tsx, frontend/src/components/DialogApp/DialogApp.tsx, frontend/src/components/DialogApp/index.ts, frontend/src/services/Browser.ts, frontend/src/services/Controller.ts, frontend/src/shared/applications.ts
Launch VNC  in Windows
1. Sign in in Windows environment with VNC installed
3. Choose a device with VNC service
4. Connect and open VNC service
5. Launch service
4. You should see VNC open
https://remoteit.atlassian.net/browse/DESK-834
=> [DESK-834] open vnc in windows

backend/src/sharedCopy/constants.ts, frontend/src/shared/constants.ts, package-lock.json, package.json
- update app name
- update API URL
https://remoteit.atlassian.net/browse/DESK-885
https://remoteit.atlassian.net/browse/DESK-902
=> [DESK-885] [DESK-902] change api url and name app

frontend/src/components/Icon/Icon.tsx
=> fix warning font ref

backend/package-lock.json, backend/package.json, backend/src/Binary.ts, backend/src/binaryInstaller.test.ts, backend/src/constants.ts, frontend/package-lock.json, frontend/package.json, installer.nsh, package-lock.json, package.json
<https://remoteit.atlassian.net/browse/DESK-913>
=> DESK-913 Change from path join to path resolve

backend/package-lock.json, backend/package.json, frontend/package-lock.json, frontend/package.json, frontend/src/store.tsx, frontend/src/styling/theme.ts, installer.nsh, package-lock.json, package.json
2.10.0 alpha.0 internal release
=> 2.10.0 alpha.0

frontend/src/components/DataDisplay/DataDisplay.tsx, frontend/src/components/DeviceSetupItem/DeviceSetupItem.tsx, frontend/src/components/FilterDrawerContent/FilterDrawerContent.tsx, frontend/src/components/Notice.tsx, frontend/src/components/ServiceName/ServiceName.tsx, frontend/src/components/SessionsList/SessionsList.tsx, frontend/src/components/SharedUsersHeader/SharedUsersHeader.tsx, frontend/src/components/Title/Title.tsx, frontend/src/pages/AccountAccessPage.tsx, frontend/src/pages/AccountMembershipPage.tsx, frontend/src/pages/AccountSharePage.tsx, frontend/src/pages/DeviceDetailPage/DeviceDetailPage.tsx, frontend/src/pages/DeviceEditPage/DeviceEditPage.tsx, frontend/src/pages/DeviceLogPage/DeviceLogPage.tsx, frontend/src/pages/LogPage/LogPage.tsx, frontend/src/pages/ServiceAddPage/ServiceAddPage.tsx, frontend/src/pages/ServiceAddPage/ServiceAddPageInline.tsx, frontend/src/pages/ServiceDetailPage/ServiceDetailPage.tsx, frontend/src/pages/ServiceEditPage/ServiceEditPage.tsx, frontend/src/pages/SharePage/SharePage.tsx, frontend/src/styling/theme.ts
Fix color sorting 
Fix icon spacing
1. Sign in
3. Click filter and sort by color
4. You should see the device list sorted by color
<https://remoteit.atlassian.net/browse/DESK-924>
=> DESK-924 sort color

frontend/src/components/ReportTimeSeriesVis/ReportTimeSeriesVis.tsx
1. Sign in
2. Go to...
3. Click...
=> Fixing y-axis scale and formatting to integer

backend/src/Command.ts, backend/src/index.ts
add params version to airbrake
https://remoteit.atlassian.net/browse/DESK-918
=> [DESK-918] airbrake version

backend/src/sharedCopy/nameHelper.ts, frontend/src/components/LanShareSelect/LanShareSelect.tsx, frontend/src/components/ServiceListItem/ServiceListItem.tsx, frontend/src/pages/LanSharePage/LanSharePage.tsx, frontend/src/pages/ServicePage/ServicePage.tsx, frontend/src/shared/nameHelper.ts
Restore host IP setting until it can be moved to lan share page
<https://remoteit.atlassian.net/browse/DESK-926>
=> DESK-926 host ip

frontend/src/models/devices.ts, frontend/src/models/licensing.ts
Update AWS link
1. Sign in
2. Go to settings page
3. Click the upgrade link
4. You should see the saas aws page
<https://remoteit.atlassian.net/browse/DESK-919>
=> DESK-919 aws link

frontend/src/components/AdminPanelConnect.tsx, frontend/src/models/devices.ts
<https://remoteit.atlassian.net/browse/DESK-903>
=> DESK-903 apostrophe error

frontend/src/components/LicensingNotice.tsx, frontend/src/components/LicensingServiceNotice.tsx, frontend/src/models/licensing.ts
show license notice just for the device owner
1. Sign in
2. Go to the device list
3. Click in one AWS device of yourself
4. You should see a message if your plan is trial
https://remoteit.atlassian.net/browse/DESK-910
=> [DESK-910] show license notice just for device owner

package.json, src/ElectronApp.ts
Allow app to go fullscreen in windows for @GeekCornerGH
=> Windows fullscreen

backend/src/index.ts, backend/src/sharedCopy/applications.ts, backend/src/sharedCopy/nameHelper.ts, frontend/src/buttons/CopyButton.tsx, frontend/src/buttons/LaunchButton/LaunchButton.tsx, frontend/src/components/CustomAttributeSettings.tsx, frontend/src/components/InlineTemplateSetting/InlineTemplateSetting.tsx, frontend/src/components/ServiceAttributesForm.tsx, frontend/src/hooks/useApplication.ts, frontend/src/shared/applications.ts, frontend/src/shared/nameHelper.ts, src/TrayMenu.ts
Support token substitution for all occurrences
1. Sign in
2. Go to a service page
3. Edit a copy command and duplicate a token
4. You should see the token replaced in all occurences
<https://remoteit.atlassian.net/browse/DESK-933>
=> DESK-933 sub all tokens

backend/src/preferences.ts, backend/src/sharedCopy/constants.ts, common/types.d.ts, frontend/src/models/auth.ts, frontend/src/pages/SettingsPage/SettingsPage.tsx, frontend/src/services/Notifications.ts, frontend/src/services/cloudController.ts, frontend/src/shared/constants.ts
- Provide notification preference to disable notices
- Use production endpoint for production ws connection
- Set to refetch device list when re-connecting
<https://remoteit.atlassian.net/browse/DESK-931>
=> DESK-931 ws final integration

frontend/src/buttons/LaunchButton/LaunchButton.tsx
Browser launch for web services no longer works
See video https://remoteit.atlassian.net/browse/DESK-925?focusedCommentId=34683
https://remoteit.atlassian.net/browse/DESK-925
=> [DESK-925] launch http

backend/src/CLI.ts, backend/src/ConnectionPool.ts, backend/src/constants.ts, frontend/src/services/Controller.ts
CLI report status
1. Sign in
2. Go to...
3. Click...
https://remoteit.atlassian.net/browse/DESK-840
=> [DESK-840] CLI reachable status

frontend/src/components/Icon/Icon.tsx, frontend/src/pages/ServicePage/ServicePage.tsx, frontend/src/services/cloudController.ts, frontend/src/services/graphQL.ts
Small fixes
1. Pass className to Icon component
2. Show connection errors open on service page
3. Suppress websocket errors
=> Small fixes

backend/package-lock.json, backend/package.json, backend/src/CLI.ts, backend/src/cli-version.json, backend/src/cliStrings.ts, backend/src/launch.ts, common/types.d.ts, frontend/package-lock.json, frontend/package.json, frontend/src/buttons/LaunchButton/LaunchButton.tsx, frontend/src/hooks/useApplication.ts, frontend/src/services/Browser.ts, installer.nsh, package-lock.json, package.json
Version bump and minor fixes
- CLI version update with -j version query
- Launch browser bug fixes
- useApplication endless loop crash fix
=> Cli 1.6.31

frontend/src/buttons/LaunchButton/LaunchButton.tsx, frontend/src/components/ReportDeviceQualityList/ReportDeviceQualityList.tsx, frontend/src/components/ShareSaveActions/ShareSaveActions.tsx, frontend/src/models/accounts.ts, frontend/src/models/analytics.ts, frontend/src/models/backend.ts, frontend/src/models/devices.ts, frontend/src/models/licensing.ts, frontend/src/models/logs.ts, frontend/src/models/shares.ts, frontend/src/models/ui.ts, frontend/src/services/Controller.ts, frontend/src/store.tsx
Fix TypeScript model definitions in component selectors
TypeScript info in useSelector((state: ApplicationState) 
https://remoteit.atlassian.net/browse/DESK-932
=> [DESK-932] fix typescript models

frontend/src/components/SharedUsersList/SharedUsersList.tsx, frontend/src/components/UserListItem/UserListItem.tsx
show linked user in access device
1. Sign in
3. Click on one of your own devices
4. Click in Shared Users
4. You should see a list of `DEVICE LIST SHARED`
https://remoteit.atlassian.net/browse/DESK-794
=> [DESK-794] show linked user in access device

backend/src/sharedCopy/constants.ts, frontend/src/components/TargetPlatform/TargetPlatform.tsx, frontend/src/helpers/platformHelper.ts, frontend/src/services/Notifications.ts, frontend/src/services/platformConfiguration.ts, frontend/src/shared/constants.ts
Target platform naming of unknown platforms
=> Target platform update

frontend/src/services/remote.it.ts
<https://remoteit.atlassian.net/browse/DESK-942>
=> DESK-942 Don't end session if getToken error has no error code

common/types.d.ts, frontend/src/buttons/RegisterButton.tsx, frontend/src/components/Body/Body.tsx, frontend/src/components/Container/Container.tsx, frontend/src/components/FilterDrawerContent/FilterDrawerContent.tsx, frontend/src/components/FilterDrawerContent/FilterSelector.tsx, frontend/src/models/devices.ts, frontend/src/services/graphQLDevice.ts, frontend/src/styling/theme.ts
Filter devices by Platform
https://remoteit.atlassian.net/browse/DESK-938
=>  DESK-867 filter platform

frontend/src/components/LicensingSetting.tsx
change text aws licensing
1. Sign in
2. Go to...
3. Click...
https://remoteit.atlassian.net/browse/DESK-941
=> [DESK-936] change text aws licensing

common/types.d.ts, frontend/src/buttons/RegisterButton.tsx, frontend/src/components/InlineTextFieldSetting/InlineTextFieldSetting.tsx, frontend/src/components/PortSetting/PortSetting.tsx, frontend/src/components/PromptModal.tsx, frontend/src/components/Scan/Scan.tsx, frontend/src/components/ServiceAttributesForm.tsx, frontend/src/components/ServiceForm/ServiceForm.tsx, frontend/src/components/TemplateSetting.tsx, frontend/src/models/accounts.ts, frontend/src/models/backend.ts, frontend/src/pages/LanSharePage/LanSharePage.tsx, frontend/src/pages/ServiceEditPage/ServiceEditPage.tsx, frontend/src/pages/SetupDevice/SetupDevice.tsx, frontend/src/styling/theme.ts
- DESK-929 Adding default port setting
- Set default values for service attributes
- Removing underline from input fields
- Fix for device list merge errors
https://remoteit.atlassian.net/browse/DESK-929
=> DESK-929 Allow configuring of default connection port

frontend/src/pages/ReportsPage/ReportsPage.tsx
1. Sign in
2. Go to...
3. Click...
=> DESK-946. Remove the total in the device summary widget

frontend/src/components/SharingForm.tsx
fix share user by service URL
=
1. Sign in
3. Choose one device
4. Go to a service in the list
5. click on the share icon
4. You should see your current service selected
=> [DESK-0000] fix share user by service URL

backend/src/Controller.ts, backend/src/Logger.ts, backend/src/cliStrings.ts, backend/src/environment.ts, backend/src/showFolder.ts, common/types.d.ts, frontend/src/components/ConnectionLogSetting.tsx, frontend/src/components/ListItemSetting/ListItemSetting.tsx, frontend/src/helpers/platformHelper.ts, frontend/src/pages/ServicePage/ServicePage.tsx, frontend/src/pages/SettingsPage/SettingsPage.tsx, package.json
1. Sign in
2. Go to a service 
3. Click the option to enable "Connection Logging"
4. Connect
5. Click the "SHOW LOG" button
6. The folder containing the connection logs should open
7. Confirm logging is happening
<https://remoteit.atlassian.net/browse/DESK-944>
=> DESK-944 connection logs

common/types.d.ts, frontend/src/components/LicensingNotice.tsx, frontend/src/components/LicensingSetting.tsx, frontend/src/models/licensing.ts
Handle if a license doesn't expire
<https://remoteit.atlassian.net/browse/DESK-943>
=> DESK-943 Handle when no license is set

frontend/src/components/SharedUsersList/SharedUsersList.tsx
fix filter user linked
1. Sign in
2. Go to...
3. Click...
=> [DESK-0000] fix filter user linked

backend/package-lock.json, backend/package.json, backend/src/CLI.ts, backend/src/cli-version.json, common/types.d.ts, frontend/package-lock.json, frontend/package.json, frontend/src/components/LicensingNotice.tsx, frontend/src/components/LicensingSetting.tsx, frontend/src/helpers/connectionHelper.ts, frontend/src/models/licensing.ts, frontend/src/services/cloudController.ts, frontend/src/services/graphQLDevice.ts, installer.nsh, package-lock.json, package.json
Resolve connection events by sessionId
1. Sign in on two machines or VMs
2. Connect to a device on one and see the notice on both and the state in the connections tab
<https://remoteit.atlassian.net/browse/DESK-940>
=> DESK-940 connection state

frontend/src/components/SharedUsersList/SharedUsersList.tsx, frontend/src/components/UsersSelect/UsersSelect.tsx, frontend/src/pages/ServicePage/ServicePage.tsx, frontend/src/pages/ServicesPage/ServicesPage.tsx
show users in the device list
1. Sign in
2. Go to...
3. Click...
https://remoteit.atlassian.net/browse/DESK-952
https://remoteit.atlassian.net/browse/DESK-951
=> [DESK-951] [DESK-952] show users in device list

frontend/src/components/UpdateSetting/UpdateSetting.tsx
Fixing auto-update restart button in settings page
=> fixing auto-update restart button in settings page

frontend/src/services/cloudController.ts
Adding heartbeat to the ws event
<https://remoteit.atlassian.net/browse/DESK-960>
=> DESK-960 ws event hearbeat

frontend/src/components/FilterDrawerContent/FilterDrawerContent.tsx
When filtering on the device list on the platform, make the list alphabetical
1. Sign in
2. Go to...
3. Click...
https://remoteit.atlassian.net/browse/DESK-948
=> [DESK-948] fix sort filter platform

backend/package-lock.json, backend/package.json, backend/src/CLI.ts, backend/src/cli-version.json, common/types.d.ts, frontend/package-lock.json, frontend/package.json, frontend/src/services/graphQLDevice.ts, installer.nsh, package-lock.json, package.json
Compare session ids as lowercase
<https://remoteit.atlassian.net/browse/DESK-960>
=> DESK-960 Sessions fix

frontend/src/pages/LanSharePage/LanSharePage.tsx
show bind ip
1. Sign in
3. Click in a service
4. Click in edit service
5. Click Local Network Sharing
6. You should see Bind IP Address
https://remoteit.atlassian.net/browse/DESK-926
=> [DESK-926] show bind ip

frontend/src/buttons/RegisterButton.tsx, frontend/src/pages/Page/Page.tsx, frontend/src/services/graphQL.ts
Handle no authorization token and display only one snackbar type at a time
<https://remoteit.atlassian.net/browse/DESK-964>
=> DESK-964 session expired error

frontend/src/components/ConnectionStateIcon/ConnectionStateIcon.tsx, frontend/src/pages/ServiceAddPage/ServiceAddPage.tsx
Fixed cloudshift service limit
1. Sign in on a device with 10 services already added
2. Click on a cloudshift device
3. Check that you can add up to 10 more services on that device as well.
<https://remoteit.atlassian.net/browse/DESK-967>
=> DESK-967 cloudshift service limit

frontend/src/models/accounts.ts, frontend/src/models/logs.ts, frontend/src/pages/DeviceLogPage/DeviceLogPage.tsx
In one of Gary's white screens we traced the error back to the log page request.
This tries to address errors that could have been introduced.
1. Sign in
2. Go to log page
3. Click logs
4. You should see logs
* Additional testing info: Multi device lists might be needed to find the bugs. And working with multi-lists.
<https://remoteit.atlassian.net/browse/DESK-953>
=> DESK-953 white screen

frontend/src/components/AnnouncementCard.tsx, frontend/src/components/Body/Body.tsx, frontend/src/components/Container/Container.tsx, frontend/src/models/announcements.ts, frontend/src/pages/AnnouncementsPage.tsx
Marking announcements read by scroll position and by clicking on a new button.
<https://remoteit.atlassian.net/browse/DESK-968>
=> DESK-968 read announcements

frontend/src/components/ServiceForm/ServiceForm.tsx
Fix service enabled ux
1. Sign in
2. Go to a service
3. Click service enabled checkbox
4. You should understand the state
<https://remoteit.atlassian.net/browse/DESK-971>
=> DESK-971 enable service ux

backend/src/CLI.ts, backend/src/Command.ts, backend/src/cli-version.json, backend/src/types.d.ts, frontend/src/components/ServiceList/ServiceList.tsx, frontend/src/components/SessionsList/SessionsList.tsx
Update to handle changes in CLI response formatting and error reporting
Also, connected user location parsing
<https://remoteit.atlassian.net/browse/DESK-976>
=> DESK-976 cli compat

frontend/package-lock.json, frontend/package.json
[DESK-963] integrate last version components
https://remoteit.atlassian.net/browse/DESK-963
https://remoteit.atlassian.net/browse/DESK-880
[DESK-963]: https://remoteit.atlassian.net/browse/DESK-963
=> [DESK-963] integrate last version components

backend/src/Command.ts
[DESK-957] ignore read-only file system error
https://remoteit.atlassian.net/browse/DESK-957
[DESK-957]: https://remoteit.atlassian.net/browse/DESK-957
=> [DESK-957] ignore read only error

frontend/src/buttons/ConnectButton/ConnectButton.tsx, frontend/src/components/ConnectionsList/ConnectionsList.tsx, src/TrayMenu.ts
1. Sign in in windows
2. Create proxy only connection
3. Wait for it to die
4. You should see listening button in the connected section in blue
<https://remoteit.atlassian.net/browse/DESK-989>
=> DESK-989 listening state bug

common/types.d.ts, frontend/src/models/logs.ts, frontend/src/pages/DeviceLogPage/DeviceLogPage.tsx
split logs state
separate logs from device
- https://remoteit.atlassian.net/browse/DESK-969
1. Sign in
2. Go to a device
3. Click logs
4. You should see logs working correctly
- https://remoteit.atlassian.net/browse/DESK-969
=> [DESK-969] split logs state

frontend/src/models/logs.ts, frontend/src/pages/DeviceLogPage/DeviceLogPage.tsx
DESK-0000-fix-logs
1. Sign in
2. Go to a device
3. Click logs
4. Click load more
5. You should see working correctly 
=> DESK-0000-fix-logs

frontend/package-lock.json, frontend/package.json, frontend/src/components/SignInForm/SignInForm.tsx, frontend/src/models/auth.ts
[DESK-748] remember username
1. Sign in
2. Logout
3. You should see your previous username on login form
https://remoteit.atlassian.net/browse/DESK-748
[DESK-748]: https://remoteit.atlassian.net/browse/DESK-748
=> [DESK-748] remember username

backend/package-lock.json, backend/package.json, backend/src/CLI.ts, backend/src/cli-version.json, backend/src/cliStrings.ts, frontend/package-lock.json, frontend/package.json, installer.nsh, package-lock.json, package.json
Require admin permissions for uninstall
1. Sign in
2. Go to settings page
3. Click uninstall
4. You should see the app uninstall the service
<https://remoteit.atlassian.net/browse/DESK-1005>
=> DESK-1005 reset admin

frontend/package.json
1. Sign in
2. Go to...
3. Click...
=> DESK-923 fix white space on login

frontend/package-lock.json, frontend/package.json, frontend/src/components/SignInForm/SignInForm.tsx
fix sign in remember and run with node 11.6.0
=> [DESK-0000] fix sign in remember

frontend/src/components/Header/Header.tsx
[DESK-1013] history buttons validations
https://remoteit.atlassian.net/browse/DESK-1013
[DESK-1013]: https://remoteit.atlassian.net/browse/DESK-1013
=> [DESK-1013] history buttons validations

frontend/src/buttons/CSVDownloadButton/CSVDownloadButton.tsx, frontend/src/components/EventList/EventIcon.tsx, frontend/src/components/EventList/EventItem.tsx, frontend/src/components/EventList/EventList.tsx, frontend/src/components/EventList/EventMessage.tsx, frontend/src/components/EventList/index.ts, frontend/src/models/logs.ts, frontend/src/pages/DeviceLogPage/DeviceLogPage.tsx, frontend/src/pages/SettingsPage/SettingsPage.tsx, frontend/src/pages/UserLogPage/UserLogPage.tsx, frontend/src/pages/UserLogPage/index.ts, frontend/src/routers/Router.tsx, frontend/src/services/graphQLLogs.ts
complete logs of the user
1. Sign in
2. Go to setting
3. Click in logs
4. You should see a new page logs
https://remoteit.atlassian.net/browse/DESK-998
https://www.sketch.com/s/9c23fbe9-993c-40d8-8a56-d8a93df032d1/a/AxPEKdz
=> Desk 998 complete logs v2

frontend/package-lock.json, frontend/package.json, frontend/src/components/SignInForm/SignInForm.tsx, frontend/src/helpers/analyticsHelper.ts
integrate segment sign up
1. Sign up
2. Go to dashboard segment
3. You should see events there
=> [DESK-0000] integrate segment sign up

backend/package-lock.json, backend/package.json, backend/src/CLI.ts, backend/src/Connection.ts, backend/src/cli-version.json, frontend/package-lock.json, frontend/package.json, frontend/src/buttons/ClearButton/ClearButton.tsx, frontend/src/buttons/DisconnectButton/DisconnectButton.tsx, frontend/src/buttons/DynamicButton/DynamicButton.tsx, frontend/src/components/RemoteHeader/RemoteHeader.tsx, frontend/src/components/SessionListItem.tsx, frontend/src/components/Sidebar/Sidebar.tsx, frontend/src/helpers/connectionHelper.ts, frontend/src/hooks/useNavigation.ts, frontend/src/pages/ConnectionsPage/ConnectionsPage.tsx, installer.nsh, package-lock.json, package.json, src/TrayMenu.ts
Update to support new CLI time/date interface
<https://remoteit.atlassian.net/browse/DESK-1036>
=> DESK-1036 cli date interface

frontend/src/buttons/LabelButton/LabelButton.tsx, frontend/src/components/AccountSelect.tsx, frontend/src/components/DoublePanel.tsx, frontend/src/components/SessionListItem.tsx, frontend/src/pages/AccountAccessPage.tsx, frontend/src/pages/ConnectionsPage/ConnectionsPage.tsx, frontend/src/pages/LanSharePage/LanSharePage.tsx, frontend/src/styling/theme.ts
- DESK-1039 Switched from using mouse movement to measuring the movement with mouse position
- DESK-1042 lan share select page route fix
- DESK-1041 fix route to device list share add user
<https://remoteit.atlassian.net/browse/DESK-1039>
<https://remoteit.atlassian.net/browse/DESK-1042>
<https://remoteit.atlassian.net/browse/DESK-1041>
=> DESK-1039 DESK-1042 DESK-1041 windows panel resizing

frontend/package-lock.json, frontend/package.json
Upgrade dependency remoteit/components to fix issues on sign in
=> Upgrade dependency remoteit/components to fix issues on sign in

frontend/src/buttons/CSVDownloadButton/CSVDownloadButton.tsx, frontend/src/components/EventList/EventList.tsx, frontend/src/components/SidebarNav.tsx, frontend/src/models/logs.ts, frontend/src/pages/UserLogPage/UserLogPage.tsx, frontend/src/services/graphQLLogs.ts
logs page add a date picker
1. Sign in
2. Go to setting
3. Click in logs
4. You should see date picker
https://remoteit.atlassian.net/browse/DESK-1043
=> [DESK-1043] logs page date picker

frontend/src/components/EventList/EventList.tsx
Handle when no log limit is set
<https://remoteit.atlassian.net/browse/DESK-1947>
=> DESK-1947 Handle when no log limit is set

frontend/package-lock.json, frontend/package.json
fix remember me, 
when a user setup password then click in remember me it event was cleaning password input
1. Open Sign in
2. Put a password
3. Click checkbox or text `Remember me`
4. You should see fill input password 
https://remoteit.atlassian.net/browse/DESK-1023
=> [DESK-1023] fix remember me

frontend/package-lock.json, frontend/package.json, frontend/src/components/SignInForm/SignInForm.tsx
[WEB-1888] add track event
[WEB-1888]: https://remoteit.atlassian.net/browse/WEB-1888
=> [WEB-1888] add track event

backend/src/Controller.ts
shupdown all agents click in restart
1. Sign in on old version 
2. You should see modal to upgrade version
3. Click restart
4. You should see that every service shutdown
https://remoteit.atlassian.net/browse/DESK-987
=> [DESK-987] shutdown all agents click in restart

frontend/package-lock.json, frontend/package.json, frontend/src/models/auth.ts
fix google sign in callback
attempt google signin
<https://remoteit.atlassian.net/browse/Desk-1018>
=> [DESK-1018] fix google sign in callback

backend/src/cli-version.json, common/types.d.ts, frontend/package-lock.json, frontend/package.json, frontend/src/buttons/ConnectButton/ConnectButton.tsx, frontend/src/buttons/RefreshButton/RefreshButton.tsx, frontend/src/components/DoublePanel.tsx, frontend/src/components/Header/Header.tsx, frontend/src/components/ListItemLocation/ListItemLocation.tsx, frontend/src/components/SidebarNav.tsx, frontend/src/hooks/useNavigation.ts, frontend/src/index.tsx, frontend/src/models/devices.ts, frontend/src/models/ui.ts, frontend/src/pages/DeviceDetailPage/DeviceDetailPage.tsx, frontend/src/pages/DevicePage.tsx, frontend/src/pages/Page/Page.tsx, frontend/src/pages/ServiceEditPage/ServiceEditPage.tsx, frontend/src/routers/DeviceRouter.tsx, frontend/src/services/Controller.ts, frontend/src/services/graphQL.ts
- CLI 1.7.23
- Offline state handling
- Display stopping connection state
- Don't allow panels to become too small with resizing a window
- Small styling updates
- Fixing page routing if service is missing
- Updating sidebar navigation active state display
1. turn off network connection
2. start the app
3. turn on network connection
4. You should see it startup normally
5. turn off network
6. you should see a notice
7. turn on it should all work again
8. delete a service
9. you should stay on the device page
<https://remoteit.atlassian.net/browse/DESK-1048>
=> DESK-1048 routing and offline

frontend/src/components/HostSetting/HostSetting.tsx
Display actual bind ip address
<https://remoteit.atlassian.net/browse/DESK-1053>
=> DESK-1053 Display actual bind ip address

backend/src/sharedCopy/constants.ts, frontend/src/helpers/lanSharing.ts, frontend/src/pages/ConnectionPage.tsx, frontend/src/pages/LanSharePage/LanSharePage.tsx, frontend/src/shared/constants.ts
bind ip edit and validation
https://remoteit.atlassian.net/wiki/x/AYBHO
https://remoteit.atlassian.net/browse/DESK-926
=> [DESK-926] bind ip edit and validation

backend/src/cli-version.json, frontend/src/hooks/useNavigation.ts, frontend/src/models/ui.ts, frontend/src/pages/AccountAccessPage.tsx, frontend/src/pages/AccountMembershipPage.tsx, frontend/src/pages/ConnectionPage.tsx, frontend/src/pages/DevicePage.tsx, frontend/src/pages/LanSharePage/LanSharePage.tsx, frontend/src/routers/DeviceRouter.tsx, frontend/src/services/Notifications.ts
- Small ux fixes to lan sharing
- Fixing navigation connection active state
- Fix navigation highlighting in remote ui mode
- Adjust side panel for device view
- Fix click to load page for notifications
<https://remoteit.atlassian.net/browse/DESK-926>
=> DESK-926 update

backend/package-lock.json, backend/package.json, frontend/package-lock.json, frontend/package.json, frontend/src/components/Duration/Duration.tsx, frontend/src/components/Formats.tsx, frontend/src/components/ServiceConnected/ServiceConnected.tsx, frontend/src/components/SessionListItem.tsx, frontend/src/pages/DeviceDetailPage/DeviceDetailPage.tsx, frontend/src/pages/ServiceDetailPage/ServiceDetailPage.tsx, frontend/src/services/Notifications.ts, installer.nsh, package-lock.json, package.json
Updating connection duration display with end time
<https://remoteit.atlassian.net/browse/DESK-1056>
=> DESK-1056 duration end time

frontend/src/components/LicensingNotice.tsx, frontend/src/components/Notice.tsx, frontend/src/models/licensing.ts
Add "Dismiss" button for expired AWS trial license
1. Sign in
2. Go to setting
3. Click on dismiss button in the notification licensing
4. You should not see the notification licensing
https://remoteit.atlassian.net/browse/DESK-1020
=> [DESK-1020] dismiss badge 

frontend/src/components/DeviceHeaderMenu.tsx, frontend/src/components/FooterNav.tsx, frontend/src/components/Header/Header.tsx, frontend/src/components/ListHorizontal.tsx, frontend/src/components/ListItemLocation/ListItemLocation.tsx, frontend/src/components/ServiceHeaderMenu.tsx, frontend/src/components/SessionListItem.tsx, frontend/src/components/SidebarNav.tsx, frontend/src/components/UsersSelect/UsersSelect.tsx, frontend/src/hooks/useNavigation.ts, frontend/src/models/ui.ts, frontend/src/pages/DevicePage.tsx, frontend/src/routers/DeviceRouter.tsx
control history event
https://remoteit.atlassian.net/browse/DESK-1013
=> [DESK-1013] control history event

frontend/src/buttons/RefreshButton/RefreshButton.tsx, frontend/src/models/logs.ts
refresh button logs
1. Sign in
3. Click on logs
4. Click the refresh button
4. You should see updated logs
https://remoteit.atlassian.net/browse/DESK-1055
=> [DESK-1055] refresh button logs

frontend/src/pages/LanSharePage/LanSharePage.tsx
fix edit setting bind ip
1. Sign in
2. Go to your current device
3. Click in a service
4. Change Local Network Sharing
5. You should see working Local Network Security
https://remoteit.atlassian.net/browse/DESK-926
=> [DESK-926] fix edit setting bind ip

frontend/src/models/shares.ts
fix message shared
1. Sign in
2. Go to...
3. Click...
https://remoteit.atlassian.net/browse/DESK-1054
=> [DESK-1054] fix message shared

backend/src/sharedCopy/constants.ts, common/types.d.ts, frontend/src/pages/DeviceDetailPage/DeviceDetailPage.tsx, frontend/src/services/graphQLDevice.ts, frontend/src/shared/constants.ts
remove legacy attributes
1. Sign in
2. Go to...
3. Click...
https://remoteit.atlassian.net/browse/DESK-993
=> [DESK-993] remove legacy attributes

frontend/src/pages/SharePage/SharePage.tsx
selected service default
https://remoteit.atlassian.net/browse/DESK-1072
=> [DESK-1072] selected service

backend/src/binaryInstaller.ts, backend/src/cliStrings.ts, backend/src/environment.ts, frontend/src/components/AvatarMenu.tsx, frontend/src/components/Container/Container.tsx, frontend/src/components/DeviceSetupItem/DeviceSetupItem.tsx, frontend/src/pages/SettingsPage/SettingsPage.tsx, src/AutoUpdater.ts
Fixed cert path resolution
<https://remoteit.atlassian.net/browse/CLI-735>
=> CLI-735 certs failing

frontend/src/helpers/lanSharing.ts
lan label restriction
1. Sign in
2. Go to your device
3. Click a service
4. Edit local network change
5. You should see the correctly label on
https://remoteit.atlassian.net/browse/DESK-1058
=> [DESK-1058] lan label restriction

backend/package-lock.json, backend/package.json, backend/src/Binary.ts, backend/src/CLI.ts, backend/src/Controller.ts, backend/src/binaryInstaller.test.ts, backend/src/binaryInstaller.ts, backend/src/headlessUpdater.ts, backend/src/preferences.ts, common/types.d.ts, frontend/package-lock.json, frontend/package.json, installer.nsh, package-lock.json, package.json
Watch cli version for change on upgrade
<https://remoteit.atlassian.net/browse/DESK-1063>
=> DESK-1063 detect cli version changing

frontend/src/components/EventList/EventHeader.tsx, frontend/src/models/logs.ts, frontend/src/services/graphQLLogs.ts
log download use eventURL to download the correct file
1. Sign in
2. Go to...
3. Click...
https://remoteit.atlassian.net/browse/DESK-1084
=> [DESK-1084] log download use eventURL to download correct file

backend/src/CLI.ts, backend/src/Command.ts
[DESK-1017] Stop logging Command Failures to Airbrake
https://remoteit.atlassian.net/browse/DESK-1017
[DESK-1017]: https://remoteit.atlassian.net/browse/DESK-1017
=> [DESK-1017] Stop logging Command Failures to Airbrake

backend/src/launch.ts, frontend/src/buttons/LaunchButton/LaunchButton.tsx, frontend/src/services/Browser.ts
RDP connection in Windows Desktop should launch the Remote Desktop Client
1. Sign in on Windows environtment 
2. Go to a device
3. Click on a service RDP
4. Click in launch
4. You should see RDP client open
https://remoteit.atlassian.net/browse/DESK-1083
=> [DESK-1083] RDP connection in Windows Desktop should launch the Remote Desktop Client

frontend/src/models/shares.ts
fix none service share
1. Sign in
2. Go to your own device
3. Click in users
4. Share zero servicies
4. You should users with zero services
https://remoteit.atlassian.net/browse/DESK-1089
=> DESK-1089 fix none service share

frontend/src/components/SortServices.tsx, frontend/src/models/devices.ts, frontend/src/pages/DevicePage.tsx
sort services
1. Sign in
2. Go to device
3. Click the new icon to sort services
4. You should see sorted services as you selected 
https://remoteit.atlassian.net/browse/DESK-1076
=> [DESK-1076] sort services

frontend/src/components/SharingForm.tsx, frontend/src/pages/SharePage/SharePage.tsx
[DESK-1107] shared resource
1. Sign in
2. Go to the device
3. Click in users
4. Share a new users
4. You should see working correctly the buttons
https://remoteit.atlassian.net/browse/DESK-1107
[DESK-1107]: https://remoteit.atlassian.net/browse/DESK-1107
=> [DESK-1107] shared resource

backend/package-lock.json, backend/package.json, backend/src/Binary.ts, backend/src/CLI.ts, backend/src/Controller.ts, backend/src/Logger.ts, backend/src/binaryInstaller.ts, backend/src/cliStrings.ts, backend/src/preferences.ts, common/types.d.ts, frontend/package-lock.json, frontend/package.json, frontend/src/buttons/ConnectButton/ConnectButton.tsx, frontend/src/buttons/CopyButton.tsx, frontend/src/buttons/IconButton.tsx, frontend/src/buttons/LaunchButton/LaunchButton.tsx, frontend/src/components/AccordionMenu.tsx, frontend/src/components/ConnectionDetails.tsx, frontend/src/components/GuideStep.tsx, frontend/src/models/ui.ts, frontend/src/pages/DevicePage.tsx, frontend/src/pages/OptionsPage.tsx, frontend/src/pages/ServiceDetailPage/ServiceDetailPage.tsx, installer.nsh, package-lock.json, package.json
DESK-1128 fix binary install handling so that it sets default on install and then only when changing the setting separately
DESK-1111 updates for on boarding guide
Disabling one http listener
<https://remoteit.atlassian.net/browse/DESK-1128>
<https://remoteit.atlassian.net/browse/DESK-1111>
=> DESK-1128 upgrading cli defaults

frontend/src/helpers/apiHelper.ts, frontend/src/pages/TestPage.tsx, frontend/src/services/cloudController.ts
[DESK-1121] set urls WEBSOCKET
https://remoteit.atlassian.net/browse/DESK-1121
[DESK-1121]: https://remoteit.atlassian.net/browse/DESK-1121
=> [DESK-1121] set urls WEBSOCKET

backend/src/launch.ts, frontend/src/services/Browser.ts
[DESK-1127] find allow use putty
https://remoteit.atlassian.net/browse/DESK-1127
[DESK-1127]: https://remoteit.atlassian.net/browse/DESK-1127
=> [DESK-1127] find allow use putty

backend/src/sharedCopy/constants.ts, frontend/src/components/EventList/EventIcon.tsx, frontend/src/components/EventList/EventMessage.tsx, frontend/src/shared/constants.ts
[DESK-1120] shares show removed
https://remoteit.atlassian.net/browse/DESK-1120
[DESK-1120]: https://remoteit.atlassian.net/browse/DESK-1120
=> [DESK-1120] shares shows removed

backend/package-lock.json, backend/package.json, common/types.d.ts, frontend/package-lock.json, frontend/package.json, frontend/src/components/AccordionMenu.tsx, frontend/src/components/App/App.tsx, frontend/src/components/AvatarMenu.tsx, frontend/src/components/ConnectionDetails.tsx, frontend/src/components/ConnectionStateIcon/ConnectionStateIcon.tsx, frontend/src/components/DeviceHeaderMenu.tsx, frontend/src/components/DeviceList/DeviceList.tsx, frontend/src/components/DeviceListEmpty/DeviceListEmpty.tsx, frontend/src/components/DeviceListItem/DeviceListItem.tsx, frontend/src/components/DeviceSetupItem/DeviceSetupItem.tsx, frontend/src/components/FilterDrawer.tsx, frontend/src/components/ServiceHeaderMenu.tsx, frontend/src/components/ServiceIndicators.tsx, frontend/src/components/ServiceName/ServiceName.tsx, frontend/src/helpers/attributes.tsx, frontend/src/models/devices.ts, frontend/src/pages/DevicePage.tsx, frontend/src/pages/DevicesPage/DevicesPage.tsx, frontend/src/pages/ServiceAddPage/ServiceAddPage.tsx, frontend/src/services/Controller.ts, frontend/src/services/graphQLDevice.ts, frontend/src/services/platformConfiguration.ts, installer.nsh, package-lock.json, package.json
- Fix on boarding initial display and update wording
- Indicate this device in device list
- save sort/filter state to local storage 
- add api links to avatar menu
<https://remoteit.atlassian.net/browse/DESK-1139>
<https://remoteit.atlassian.net/browse/DESK-1138>
=> DESK-1139 DESK-1138 onboarding updates

common/types.d.ts, frontend/src/components/GuideStep.tsx, frontend/src/models/ui.ts, frontend/src/services/Browser.ts, frontend/src/services/Controller.ts, frontend/src/services/cloudController.ts
- Adding explicit active state and saving to local storage for guides
- Adding tracking header to websocket authentication MOB-550
=> MOB-550 On boarding guide fixes

frontend/src/components/ContactCard.tsx, frontend/src/components/SharingForm.tsx
[DESK-1126] disabled save button
1. Sign in
2. Go to device
3. Click on share users 
4. You should see messages 
https://remoteit.atlassian.net/browse/DESK-1126
[DESK-1126]: https://remoteit.atlassian.net/browse/DESK-1126
https://remoteit.atlassian.net/browse/DESK-1106
=> [DESK-1126] disabled save button

frontend/src/pages/SharePage/SharePage.tsx
[DESK-1106] unshare services
1. Sign in
2. Go to the device
3. Click in users
4. Unshare services to users
4. You should see working correctly
https://remoteit.atlassian.net/browse/DESK-1106
[DESK-1106]: https://remoteit.atlassian.net/browse/DESK-1106
=> [DESK-1106] unshare services

frontend/src/pages/LanSharePage/LanSharePage.tsx
Fix display of IP mask value
<https://remoteit.atlassian.net/browse/DESK-1154>
=> DESK-1154 ip mask

backend/src/server.ts, backend/src/sharedCopy/constants.ts, frontend/src/models/auth.ts, frontend/src/shared/constants.ts, src/ElectronApp.ts
fix google sign in
test google sign in from within app and remote connected
<https://remoteit.atlassian.net/browse/Desk-1109>
=> [Desk-1109] fix google sign in

backend/src/ConnectionPool.ts, src/TrayMenu.ts
Tray menu controls function updates
<https://remoteit.atlassian.net/browse/DESK-1149>
=> DESK-1149 tray menu controls

frontend/src/buttons/CommandButton.tsx
Fixing copy command button
<https://remoteit.atlassian.net/browse/DESK-1168>
=> DESK-1168 Fixing copy command button

frontend/src/components/DevicesHeader.tsx, frontend/src/models/devices.ts, frontend/src/pages/DevicesPage/DevicesPage.tsx
Hiding device ownership message until device list is loaded
https://remoteit.slack.com/archives/CB9AHUX4L/p1628527120071900
=> Hiding device ownership message until device list is loaded

backend/package-lock.json, backend/package.json, backend/src/CLI.ts, backend/src/ConnectionPool.ts, frontend/package-lock.json, frontend/package.json, frontend/src/components/Sidebar/Sidebar.tsx, frontend/src/components/SidebarNav.tsx, frontend/src/pages/ConnectionsPage/ConnectionsPage.tsx, frontend/src/services/Heartbeat.ts, installer.nsh, package-lock.json, package.json
- Longer elevated heartbeat duration on connect
- Fix feedback menu when in remote ui
- Show new connection dialog if network tab is empty
=> More caffeine

backend/src/cliStrings.ts, frontend/src/components/ServiceName/ServiceName.tsx, frontend/src/components/SessionListItem.tsx, frontend/src/components/TargetPlatform/TargetPlatform.tsx, frontend/src/helpers/platformHelper.ts
Cleanup for release:
- Remove conditional port from cli commands
- Fix target platform 0 display bug
=> Cleanup for release

backend/package-lock.json, backend/package.json, backend/src/ConnectionPool.ts, frontend/package-lock.json, frontend/package.json, installer.nsh, package-lock.json, package.json
Fixing host name migration issues from v3.0.2
=> Connection migration

frontend/src/components/PromptModal.tsx
[DESK-1200] SSH username disappears
https://remoteit.atlassian.net/browse/DESK-1200
[DESK-1200]: https://remoteit.atlassian.net/browse/DESK-1200
=> [DESK-1200] SSH username disappears

src/ElectronApp.ts
[DESK-1204] headless no autoupdate
tar -xf remoteit-headless.tgz
node package/build
checked update should be avoid
https://remoteit.atlassian.net/browse/DESK-1204
[DESK-1204]: https://remoteit.atlassian.net/browse/DESK-1204
=> [DESK-1204] headless no autoupdate

frontend/src/services/Notifications.ts
notifications settin fix
Ref: https://github.com/remoteit/mobile/pull/285/files
=> [MOB-591] notifications settin fix

package.json, readme.md, scripts/build.sh
[DESK-1188] build by arch params
- npm run build --arch=arm64
- npm run build --arch=win
- npm run build --arch=mac
- npm run build --arch=armv7l
https://remoteit.atlassian.net/browse/DESK-1188
[DESK-1188]: https://remoteit.atlassian.net/browse/DESK-1188
=> [DESK-1188] build by arch params

common/types.d.ts, frontend/src/components/GlobalSearch.tsx, frontend/src/components/Header/Header.tsx, frontend/src/components/TargetPlatform/TargetPlatform.tsx, frontend/src/models/search.ts, frontend/src/styling/theme.ts
Global search improvements
<https://remoteit.atlassian.net/browse/DESK-1228>
=> DESK-1228 quick search enhancements

backend/src/Controller.ts, backend/src/launch.ts, backend/src/sharedCopy/applications.ts, common/types.d.ts, frontend/src/buttons/LaunchButton/LaunchButton.tsx, frontend/src/components/ConnectionDetails.tsx, frontend/src/components/DialogApp/DialogApp.tsx, frontend/src/components/LaunchSelect/LaunchSelect.tsx, frontend/src/components/LaunchSelect/index.tsx, frontend/src/models/connections.ts, frontend/src/models/ui.ts, frontend/src/pages/ConnectionOtherPage.tsx, frontend/src/pages/ConnectionPage.tsx, frontend/src/services/Browser.ts, frontend/src/shared/applications.ts
[DESK-1142] SSH launch
https://remoteit.atlassian.net/browse/DESK-1142
[DESK-1142]: https://remoteit.atlassian.net/browse/DESK-1142
=> [DESK-1142] SSH launch

frontend/src/models/shares.ts
update list user after update sharing form
1. Sign in
3. Click on users
4. ADD or REMOVE users
5. Click on Save
4. You should see list of users updated
No task
=> [DESK-0000] update list user after update sharing form

frontend/src/hooks/useNavigation.ts
[DESK-1219] fix double call state ui
1. Sign in
2. Go to any path
3.  You should see navigation path working correctly
https://remoteit.atlassian.net/browse/DESK-1219
[DESK-1219]: https://remoteit.atlassian.net/browse/DESK-1219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DESK-1219] fix double call state ui

frontend/src/components/Header/Header.tsx, frontend/src/hooks/useNavigation.ts
[DESK-1219] fix(): routing react
1. Sign in
2. Do navigation on the apps
3. Click on navigationBack or navigationForward
4. You should see working better history navigation
https://remoteit.atlassian.net/browse/DESK-1219
[DESK-1219]: https://remoteit.atlassian.net/browse/DESK-1219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DESK-1219] fix(): routing react

frontend/src/components/EventList/EventIcon.tsx, frontend/src/components/EventList/EventMessage.tsx
[DESK-1242] logs info update
https://remoteit.atlassian.net/browse/DESK-1242
[DESK-1242]: https://remoteit.atlassian.net/browse/DESK-1242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DESK-1242] logs info update

backend/src/sharedCopy/applications.ts, frontend/src/components/DialogApp/DialogApp.tsx, frontend/src/shared/applications.ts
[DESK-1259] find and launch VNC
https://remoteit.atlassian.net/browse/DESK-1259
[DESK-1259]: https://remoteit.atlassian.net/browse/DESK-1259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DESK-1259] find and launch VNC

frontend/src/components/ContactSelector.tsx, frontend/src/components/SharingForm/SharingForm.tsx, frontend/src/models/shares.ts
[DESK-1247] share save button disabled without users
https://remoteit.atlassian.net/browse/DESK-1247
[DESK-1247]: https://remoteit.atlassian.net/browse/DESK-1247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DESK-1247] share save button disabled without users

frontend/src/components/EventList/EventMessage.tsx
=> DESK-1242 logs info update

backend/src/sharedCopy/applications.ts, frontend/src/shared/applications.ts
[DESK-0000] fix() vncviewer open
=> [DESK-0000] fix() vncviewer open

frontend/src/components/UpdateNotice/UpdateNotice.tsx, frontend/src/models/accounts.ts, frontend/src/models/auth.ts, frontend/src/models/connections.ts, frontend/src/models/devices.ts, frontend/src/models/ui.ts, frontend/src/services/Browser.ts
[DESK-1237] local storage by user
https://remoteit.atlassian.net/browse/DESK-1237
[DESK-1237]: https://remoteit.atlassian.net/browse/DESK-1237?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DESK-1237] local storage by user

backend/package-lock.json, backend/package.json, backend/src/server.ts, frontend/package-lock.json, frontend/package.json, frontend/src/components/ConnectionLogSetting.tsx, frontend/src/components/Icon/Icon.tsx, frontend/src/components/InlineSelectSetting/InlineSelectSetting.tsx, frontend/src/components/InlineSetting/InlineSetting.tsx, frontend/src/components/InlineTextFieldSetting.tsx, frontend/src/components/LanShareSelect/LanShareSelect.tsx, frontend/src/components/LaunchSelect/LaunchSelect.tsx, frontend/src/components/ListItemSetting/ListItemSetting.tsx, frontend/src/components/NameSetting/NameSetting.tsx, frontend/src/components/OrganizationMember.tsx, frontend/src/components/ProxySetting/ProxySetting.tsx, frontend/src/components/PublicSetting.tsx, frontend/src/components/ServiceAttributesForm.tsx, frontend/src/components/Sidebar/Sidebar.tsx, frontend/src/components/TargetHostSetting.tsx, frontend/src/components/TimeoutSetting.tsx, frontend/src/helpers/connectionHelper.ts, frontend/src/models/auth.ts, frontend/src/routers/DeviceRouter.tsx, frontend/src/routers/Router.tsx, frontend/src/services/Controller.ts, installer.nsh, package-lock.json, package.json
- Fix small screen route to options page
- Fix login check by username and make by guid
- Improved remove org user message
- Fixed lan share route from service connect page
- Fixed connection name sanitization
- Made modified connection settings visible
<https://remoteit.atlassian.net/browse/DESK-1271>
<https://remoteit.atlassian.net/browse/DESK-1272>
<https://remoteit.atlassian.net/browse/DESK-1268>
<https://remoteit.atlassian.net/browse/DESK-1255>
=> DESK-1255 DESK-1268 DESK-1272 DESK-1271 Fix small screen route to options page

frontend/src/components/SharingForm/SharingForm.tsx
[DESK-1265] help messagge
https://remoteit.atlassian.net/browse/DESK-1265
[DESK-1265]: https://remoteit.atlassian.net/browse/DESK-1265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DESK-1265] help messagge

backend/src/sharedCopy/constants.ts, frontend/src/components/SignInForm/SignInForm.tsx, frontend/src/helpers/analyticsHelper.ts, frontend/src/shared/constants.ts
[DESK-1280] change segment key in portal
https://remoteit.atlassian.net/browse/DESK-1280
[DESK-1280]: https://remoteit.atlassian.net/browse/DESK-1280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DESK-1280] change segment key in portal

backend/src/constants.ts, backend/src/environment.ts, scripts/build.sh, scripts/installCli.sh
[DESK-0000] fix build unix
1. Build in Unix
2. You should see 3 builds for unix [arm64, amd64, armv7l]
=> [DESK-0000] fix build unix

frontend/src/models/feedback.ts, frontend/src/services/Feedback.ts
[DESK-1295] zendesk create fix
1. Sign in
2. Go to feedBack
3. Send a new feedback
4. You should see working it correctly
https://remoteit.atlassian.net/browse/DESK-1295
[DESK-1295]: https://remoteit.atlassian.net/browse/DESK-1295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DESK-1295] zendesk create fix

backend/src/sharedAdaptor.ts, backend/src/sharedCopy/applications.ts, common/types.d.ts, frontend/src/buttons/CommandButton.tsx, frontend/src/components/ConnectionDetails.tsx, frontend/src/components/ConnectionInfo.tsx, frontend/src/helpers/attributes.tsx, frontend/src/models/connections.ts, frontend/src/shared/applications.ts, frontend/src/sharedAdaptor.ts
- Handle reverse proxy connection launching in portal mode
<https://remoteit.atlassian.net/browse/DESK-1296>
=> DESK-1296 Handle reverse proxy connection launching in portal mode

backend/src/ConnectionPool.ts, backend/src/Controller.ts, frontend/src/helpers/connectionHelper.ts, frontend/src/models/backend.ts, frontend/src/models/devices.ts, frontend/src/models/ui.ts, frontend/src/services/Controller.ts, frontend/src/styling/index.ts
Protect against race conditions where removal of connections occurs
<https://remoteit.atlassian.net/browse/DESK-1299>
=> DESK-1299 only clear connections if the id's were asked for and not returned

backend/package-lock.json, backend/package.json, frontend/package-lock.json, frontend/package.json, frontend/src/components/ServiceForm/ServiceForm.tsx, installer.nsh, package-lock.json, package.json
DESK-1301 default name for registered services should use name
<https://remoteit.atlassian.net/browse/DESK-1301>
=> DESK-1301 default name for registered services should use name

backend/package-lock.json, backend/package.json, backend/src/ConnectionPool.ts, frontend/package-lock.json, frontend/package.json, frontend/src/buttons/RegisterButton.tsx, frontend/src/components/DevicesHeader.tsx, frontend/src/components/Icon/Icon.tsx, frontend/src/components/Logo/Logo.tsx, frontend/src/components/ReportSummaryBox/ReportSummaryBox.tsx, frontend/src/models/devices.ts, frontend/src/pages/DownloadDesktopPage.tsx, frontend/src/pages/SetupDevice/SetupDevice.tsx, frontend/src/pages/SetupLinuxPage.tsx, frontend/src/routers/Router.tsx, frontend/src/services/Browser.ts, frontend/src/services/Heartbeat.ts, installer.nsh, package-lock.json, package.json
**"+" Add device:** 
- this device
- Linux and Raspberry Pi
- Windows
- Mac
<https://remoteit.atlassian.net/browse/DESK-1316>
=> DESK-1316 add device

frontend/src/buttons/RefreshButton/RefreshButton.tsx, frontend/src/services/Browser.ts, frontend/src/services/Heartbeat.ts, frontend/src/services/Network.ts
Improve refresh data logic
<https://remoteit.atlassian.net/browse/WEB-2102>
=> WEB-2102 Improved sleep detection and reconnect logic

frontend/src/components/Attributes.tsx, frontend/src/components/Avatar/Avatar.tsx, frontend/src/components/AvatarMenu.tsx, frontend/src/components/Tag.tsx
Added "Access" column to device list because it was simple.
=> Adding access column to device list

backend/src/sharedCopy/applications.ts, frontend/src/components/AutocompleteMenu.tsx, frontend/src/components/ConnectionDetails.tsx, frontend/src/components/DeviceActionsBar.tsx, frontend/src/components/LaunchSelect/LaunchSelect.tsx, frontend/src/helpers/selectedHelper.ts, frontend/src/models/backend.ts, frontend/src/shared/applications.ts
Adding ability to display copy command for windows portal
1. Sign in on windows portal
2. Go to a connection
3. You should be defaulted to a connection command and be able to copy the command
<https://remoteit.atlassian.net/browse/DESK-1374>
=> DESK-1374 Adding ability to display copy command for windows portal

frontend/src/components/DeviceNameSetting/DeviceNameSetting.tsx, frontend/src/shared/nameHelper.ts
remove filter on device name to allow all unicode characters
<https://remoteit.atlassian.net/browse/DESK-1393>
=> [DESK-1393] remove filter on device name

frontend/package-lock.json, frontend/package.json
[WEB-2118] Fix sign in page on saml error
<https://remoteit.atlassian.net/browse/WEB-2118>
[WEB-2118]: https://remoteit.atlassian.net/browse/WEB-2118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2118] Fix sign in page on saml error

frontend/src/models/ui.ts, frontend/src/pages/NotificationsPage/NotificationsMode.tsx
Render notification ui screen based on the state value and also while App is refreshed
1. Sign in
2. Go to...
3. Click...
<https://remoteit.atlassian.net/browse/DESK-1328>
=> [DESK-1328] notification state updates

frontend/src/models/organization.ts, frontend/src/pages/OrganizationSettingsPage.tsx
Added domain check button and moved require saml to saml section
=> Added domain check button and moved require saml to saml section

frontend/src/components/InlineSetting/InlineSetting.tsx, frontend/src/components/SeatsSetting.tsx, frontend/src/models/plans.ts, frontend/src/services/graphQLMutation.ts
update subscription fix for org admins and ux improvements
<https://remoteit.atlassian.net/browse/DESK-1433>
=> DESK-1433 update subscription fix for org admins and ux improvements

frontend/src/models/organization.ts
Fixed revoking admin permissions bug
<https://remoteit.atlassian.net/browse/DESK-1435>
=> DESK-1435 fix revoking admin permissions

frontend/src/components/AccountSelect.tsx, frontend/src/components/EventList/EventHeader.tsx, frontend/src/components/Plans.tsx, frontend/src/models/logs.ts, frontend/src/models/plans.ts, frontend/src/pages/PlansPage.tsx, frontend/src/services/graphQLLogs.ts
Plans update & Logs per organization
=> Plans update & Logs per organization

frontend/src/buttons/IconButton.tsx, frontend/src/components/AvatarMenu.tsx, frontend/src/components/RegisterMenu.tsx, frontend/src/pages/SetupLinuxPage.tsx, frontend/src/routers/Router.tsx
Fix add device to require MANAGE permission instead of ADMIN
<https://remoteit.atlassian.net/browse/DESK-1436>
=> DESK-1436 Fix add device to require MANAGE permission instead of ADMIN

frontend/src/services/Notifications.ts, frontend/src/services/cloudController.ts
Guard against unknown target events
=> Guard against unknown target events

frontend/package-lock.json, frontend/package.json, frontend/src/components/ContactSelector.tsx, frontend/src/pages/NotificationsPage/NotificationsMode.tsx
Add improved email validation that can handle '+' plus sign in addresses
=> Add improved email validation that can handle '+' plus sign in addresses

backend/src/sharedCopy/applications.ts, frontend/src/buttons/ConnectButton/ConnectButton.tsx, frontend/src/pages/OrganizationRolePage.tsx, frontend/src/pages/ServiceEditPage/ServiceEditPage.tsx, frontend/src/shared/applications.ts
Testing fixes
- DESK-1447 Complete setting of windows default launch type
- DESK-1450 fix spelling
- DESK-1453 remove + launch from unauthorized connections
- DESK-1456 trying to ensure device is fully updated before continuing
<https://remoteit.atlassian.net/browse/DESK-1447>
<https://remoteit.atlassian.net/browse/DESK-1450>
<https://remoteit.atlassian.net/browse/DESK-1453>
<https://remoteit.atlassian.net/browse/DESK-1456>
=> DESK-1447 DESK-1450 DESK-1453 DESK-1456 testing fixes

backend/package-lock.json, backend/package.json, frontend/package-lock.json, frontend/package.json, frontend/src/components/OrganizationMember.tsx, frontend/src/helpers/apiHelper.ts, frontend/src/models/ui.ts, frontend/src/pages/OrganizationSettingsPage.tsx, frontend/src/pages/TagsPage.tsx, installer.nsh, package-lock.json, package.json
DESK-1465 setup saml instructions links in all states 
DESK-1463 display tag name to be deleted in dialog
DESK-1461 add email address of org member to remove
<https://remoteit.atlassian.net/browse/DESK-1465>
<https://remoteit.atlassian.net/browse/DESK-1463>
<https://remoteit.atlassian.net/browse/DESK-1461>
=> DESK-1465 DESK-1463 DESK-1461 saml instructions

scripts/installCli.sh
Update naming convention
https://remoteit.atlassian.net/browse/CLI-820
=> fix the naming

frontend/src/components/Plans.tsx, frontend/src/types.d.ts
1. Sign in
2. Go to...
3. Click...
<https://remoteit.atlassian.net/browse/DESK-1430>
=> [DESK-1430] plan upgrade

frontend/src/components/AccordionMenuItem.tsx, frontend/src/components/AccountSelect.tsx, frontend/src/components/OrganizationSelect.tsx, frontend/src/components/SharingForm/SharingForm.tsx, frontend/src/components/SidebarNav.tsx, frontend/src/models/devices.ts, frontend/src/models/shares.ts, frontend/src/pages/OrganizationMembershipPage.tsx, frontend/src/pages/SetupWaiting/SetupWaiting.tsx, frontend/src/pages/SharePage/SharePage.tsx, frontend/src/routers/Router.tsx, frontend/src/styling/theme.ts
Fix shared users state updating so that duplicates don't appear.
<https://remoteit.atlassian.net/browse/DESK-1484>
=> DESK-1484 simplify sharing state update and minor style tweaks

frontend/src/components/AttributeValue.tsx, frontend/src/components/Scan/Scan.tsx, frontend/src/models/devices.ts, frontend/src/pages/NetworkPage/NetworkPage.tsx, frontend/src/pages/SetupLinuxPage.tsx
<https://remoteit.atlassian.net/browse/DESK-1486>
=> DESK-1486 Fix one line install fetching for orgs + style fixes

frontend/src/components/AvatarMenu.tsx, frontend/src/components/RegisterMenu.tsx, frontend/src/models/feedback.ts, frontend/src/pages/FeedbackPage.tsx, package-lock.json
Added custom subject to feedback form
<https://remoteit.atlassian.net/browse/DESK-1492>
=> DESK-1492 adding custom subject to feedback form

frontend/src/components/Connect.tsx, frontend/src/components/ConnectionDetails.tsx, frontend/src/components/DesktopUI.tsx, frontend/src/components/Notice.tsx, frontend/src/components/OrganizationSelect.tsx, frontend/src/components/PortalUI.tsx, frontend/src/components/PublicSetting.tsx, frontend/src/models/connections.ts
- Desktop promo portal messages
- Display connection error with connection for portal connect failures
<https://remoteit.atlassian.net/browse/DESK-1494>
=> DESK-1494 desktop promos

frontend/src/components/RegisterMenu.tsx
Portal handling for the add "this" device menu item.
=> Adding this device portal handling

backend/package-lock.json, backend/package.json, frontend/package-lock.json, frontend/package.json, frontend/src/components/RegisterMenu.tsx, frontend/src/models/organization.ts, frontend/src/platforms/azure/index.tsx, installer.nsh, package-lock.json, package.json
- Fix add AWS name
- Move Register permission under user permissions
- Fix AXIS icon appearing as Azure
- Version update
=> Demo feedback

frontend/src/components/AddDevice.tsx, frontend/src/components/RegisterMenu.tsx
- implement registration permissions
<https://remoteit.atlassian.net/browse/DESK-1497>
=> DESK-1497 implement registration permissions

backend/src/sharedCopy/constants.ts, frontend/src/components/EventList/EventIcon.tsx, frontend/src/components/EventList/EventMessage.tsx, frontend/src/shared/constants.ts
Add event for password reset confirm
<https://remoteit.atlassian.net/browse/RC-1904>
=> [RC-1904] Add event for password reset confirm

frontend/src/components/ProxySetting/ProxySetting.tsx, frontend/src/helpers/connectionHelper.ts, frontend/src/pages/ConnectionDefaultsPage.tsx, frontend/src/styling/theme.ts
- Load form on page load or form change
- Honor public route default settings and indicate default option
<https://remoteit.atlassian.net/browse/DESK-1511>
<https://remoteit.atlassian.net/browse/DESK-1510>
=> DESK-1511 DESK-1510 global defaults fix

frontend/src/models/user.ts, frontend/src/pages/ProfilePage.tsx
fix selected language display
<https://remoteit.atlassian.net/browse/DESK-1517>
=> DESK-1517 fix selected language display

frontend/src/components/GlobalSearch.tsx
show search dropdown when search is in focus
<https://remoteit.atlassian.net/browse/DESK-1516>
=> DESK-1516 show search dropdown when focused

frontend/src/components/ServiceForm/ServiceForm.tsx
Setting default service port on creating a new service
=> Setting default service port on creating a new service

frontend/src/components/Connect.tsx, frontend/src/components/GuideStep.tsx, frontend/src/components/Sidebar.tsx, frontend/src/models/ui.ts
Adding to onboard guide instructions on how to add first device
=> Adding to onboard guide instructions on how to add first device

.circleci/config.yml, backend/package-lock.json, backend/package.json, backend/src/Application.ts, backend/src/Controller.ts, backend/src/Logger.ts, backend/src/electronInterface.ts, frontend/package-lock.json, frontend/package.json, frontend/src/components/App/App.tsx, frontend/src/components/ListItemSetting/ListItemSetting.tsx, frontend/src/components/UpdateNotice/UpdateNotice.tsx, frontend/src/components/UpdateSetting/UpdateSetting.tsx, frontend/src/models/backend.ts, frontend/src/models/ui.ts, frontend/src/pages/OptionsPage.tsx, frontend/src/services/Controller.ts, installer.nsh, package-lock.json, package.json, scripts/version.sh, src/AutoUpdater.ts, src/ElectronApp.ts
I added an uninstalling screen, and an extra electron quit. It seemed like the normal update and restart was sometimes leaving the app running in the activity monitor even though the icon would disappear.
=> Auto update message

frontend/src/routers/Router.tsx
Redirect sign-in url to devices
<https://remoteit.atlassian.net/browse/DESK-1536>
=> DESK-1536 redirect sign-in url to devices

backend/package-lock.json, backend/package.json, frontend/package-lock.json, frontend/package.json, frontend/src/routers/Router.tsx, installer.nsh, package-lock.json, package.json
redirect all unhandled urls to /devices
<https://remoteit.atlassian.net/browse/DESK-1536>
=> DESK-1536 sign in redirect better

frontend/package-lock.json, frontend/package.json
Fix failed account registration with white space at end or beginning of password.
<https://remoteit.atlassian.net/browse/DESK-1537>
=> [DESK-1537] Trim password to prevent error on cognito submit

backend/package-lock.json, backend/package.json, backend/src/ConnectionPool.ts, frontend/package-lock.json, frontend/package.json, installer.nsh, package-lock.json, package.json
- Migrate error condition connection data
=> Migrate error condition connection data

frontend/package.json, frontend/src/cognito/types.d.ts, frontend/src/models/auth.ts, frontend/src/models/user.ts, frontend/src/services/remote.it.ts
1. Sign in
2. Go to...
3. Click...
=> [DESK-1512] remove remote.it use

backend/package-lock.json, backend/package.json, frontend/package-lock.json, frontend/package.json, frontend/src/components/Body.tsx, frontend/src/components/Connect.tsx, frontend/src/components/ConnectionDetails.tsx, frontend/src/components/DeviceList/DeviceList.tsx, frontend/src/components/GuideBubble.tsx, frontend/src/components/Header/Header.tsx, frontend/src/components/LoadingMessage/LoadingMessage.tsx, frontend/src/components/RegisterMenu.tsx, frontend/src/components/Sidebar.tsx, frontend/src/components/UsersTab.tsx, frontend/src/models/ui.ts, frontend/src/pages/DevicePage.tsx, frontend/src/pages/NetworksPage.tsx, frontend/src/pages/OrganizationGuestPage.tsx, frontend/src/pages/SetupDevice/SetupDevice.tsx, frontend/src/pages/SetupWaiting/SetupWaiting.tsx, frontend/src/pages/TestPage.tsx, frontend/src/styling/theme.ts, installer.nsh, package-lock.json, package.json
- Updated guide bubbles
- Only show guide bubbles for users created after 2022-09-20
- Completed removal of legacy remote.it library
=> 3.12.0 beta

frontend/src/components/AccountAccessKey/AccountAccessKey.tsx, frontend/src/components/AnnouncementCard.tsx, frontend/src/components/Attributes.tsx, frontend/src/components/Duration/Duration.tsx, frontend/src/components/EventList/EventItem.tsx, frontend/src/components/FormDisplay.tsx, frontend/src/components/Invoices.tsx, frontend/src/components/LicensingNoticeDisplay.tsx, frontend/src/components/LicensingSetting.tsx, frontend/src/components/ServiceAttributes.tsx, frontend/src/components/Timestamp.tsx, frontend/src/pages/AddPage.tsx, frontend/src/pages/ProfilePage.tsx, frontend/src/services/cloudController.ts
- Fix date display in correct locale on windows
- Added created date to user, device and service
- re-sync device state on network reconnect
=> Optimizations

backend/src/preferences.ts, backend/src/server.ts, common/types.d.ts, frontend/src/buttons/AddUserButton/AddUserButton.tsx, frontend/src/buttons/IconButton.tsx, frontend/src/components/DeviceDescriptionSetting.tsx, frontend/src/components/DeviceHeaderMenu.tsx, frontend/src/components/DeviceNameSetting/DeviceNameSetting.tsx, frontend/src/components/DeviceOptionMenu.tsx, frontend/src/components/EmptyMessage.tsx, frontend/src/components/InlineTextFieldSetting.tsx, frontend/src/components/Notice.tsx, frontend/src/components/ServiceForm/ServiceForm.tsx, frontend/src/components/ServiceHeaderMenu.tsx, frontend/src/components/SharedUsersLists.tsx, frontend/src/pages/DeviceDetailPage/DeviceDetailPage.tsx, frontend/src/pages/DeviceEditPage.tsx, frontend/src/pages/NoConnectionPage.tsx, src/ElectronApp.ts
Improving share visibility and adding add member to empty user page
=> Improving share visibility and adding add member to empty user page

common/types.d.ts, frontend/src/services/cloudController.ts
Release patch to to address device loading on unloaded device state changes. Will now only load if the device created date is within a minute of the event time.
=> Release hot patch

frontend/package-lock.json, frontend/package.json, frontend/src/components/GlobalSearch.tsx, frontend/src/components/TagAutocomplete.tsx, frontend/src/shared/nameHelper.ts
https://remoteit.slack.com/archives/C4NNAG55H/p1666383548278909
=> Fixing unescaped regex crashing

backend/package-lock.json, backend/package.json, frontend/package-lock.json, frontend/package.json, frontend/src/buttons/ColumnsButton.tsx, frontend/src/buttons/FilterButton/FilterButton.tsx, frontend/src/buttons/RefreshButton/RefreshButton.tsx, frontend/src/components/ColumnsDrawer.tsx, frontend/src/components/ConnectLinkSetting.tsx, frontend/src/components/Container/Container.tsx, frontend/src/components/Drawer.tsx, frontend/src/components/FilterDrawer.tsx, frontend/src/components/Header/Header.tsx, frontend/src/models/connections.ts, frontend/src/models/ui.ts, frontend/src/services/graphQLDevice.ts, installer.nsh, package-lock.json, package.json
- Fixing build failure for arm macs by downgrading electron
- Added service quality to preload query
- Fixed persistent link enabled state loading 
- Small improvement to device list sidebar performance
=> Build 3.13.2

backend/package-lock.json, backend/package.json, frontend/package-lock.json, frontend/package.json, frontend/src/components/ServiceForm/ServiceForm.tsx, frontend/src/pages/ServiceAddPage/ServiceAddPage.tsx, installer.nsh, package-lock.json, package.json, src/index.ts
- Fixing quit function not working from avatar menu
- Fixing add service form not detecting changed
- Version bump
=> Build 3.13.4

backend/package-lock.json, backend/package.json, frontend/package-lock.json, frontend/package.json, frontend/src/models/connections.ts, frontend/src/services/graphQLMutation.ts, installer.nsh, package-lock.json, package.json
Remove session id from connect query and merge with publicId
=> Remove session id from connect query and merge with publicId

backend/src/User.ts, backend/src/preferences.ts, backend/src/sharedCopy/constants.ts, common/types.d.ts, frontend/src/components/AvatarMenu.tsx, frontend/src/components/TestUI.tsx, frontend/src/helpers/apiHelper.ts, frontend/src/models/backend.ts, frontend/src/models/ui.ts, frontend/src/models/user.ts, frontend/src/pages/TestPage.tsx, frontend/src/services/cloudController.ts, frontend/src/services/graphQL.ts, frontend/src/shared/constants.ts
Add ability to enter custom graphQL headers
=> Test headers

frontend/src/models/devices.ts, frontend/src/models/networks.ts, frontend/src/pages/AddPlatformPage.tsx, src/AutoUpdater.ts
- Fixed network device data from appearing / affecting device list
- If update to pre-release versions of desktop check for updates every check
=> Fixing networks colliding with device list

frontend/src/cognito/components/SignIn/SignIn.tsx, frontend/src/cognito/components/SignUp/SignUp.tsx
SEC-177 Added maxLength for 254 for email input
<https://remoteit.atlassian.net/browse/SEC-177>
=> SEC-177 Added maxLength for 254 for email input

.github/workflows/build.yml
Merging into main so I can pull it into the typescript-fixes branch.
=> Buildtests

backend/package-lock.json, backend/package.json, backend/src/launch.ts, backend/src/sharedAdaptor.ts, backend/src/sharedCopy/applications.ts, frontend/package-lock.json, frontend/package.json, frontend/src/components/Header/Header.tsx, frontend/src/helpers/connectionHelper.ts, frontend/src/models/networks.ts, frontend/src/models/tags.ts, frontend/src/shared/applications.ts, frontend/src/sharedAdaptor.ts, frontend/src/styling/theme.ts, installer.nsh, package-lock.json, package.json, scripts/notarize.js, scripts/sign.js
- Fixing reverse proxy detection and handling
- Fixing connection count in sidebar
- Fixing redux model modification error on network tag editing
- Fixing drag-able header overlapping buttons
- Improving signing and notarising output
=> Release 3.15.2

backend/package-lock.json, backend/package.json, backend/src/sharedCopy/applications.ts, backend/src/sharedCopy/constants.ts, frontend/package-lock.json, frontend/package.json, frontend/src/components/DoublePanel.tsx, frontend/src/components/DragAppRegion.tsx, frontend/src/components/ErrorBoundary.tsx, frontend/src/components/GlobalSearch.tsx, frontend/src/components/Header/Header.tsx, frontend/src/components/OrganizationMember.tsx, frontend/src/index.tsx, frontend/src/services/graphQLDevice.ts, frontend/src/shared/applications.ts, frontend/src/shared/constants.ts, frontend/src/store.tsx, frontend/src/styling/error.css, frontend/src/styling/theme.ts, installer.nsh, package-lock.json, package.json
- Remove TCP service types default launching with URL
- Adding error handling and airbrake reporting
- Prevent selecting an org member when assigning a role
- Update drag region css to not use kebab case
=> Release 3.15.3

frontend/src/buttons/ClearButton/ClearButton.tsx, frontend/src/components/ErrorBoundary.tsx, frontend/src/components/FilterDrawer.tsx, frontend/src/components/ListItemLocation/ListItemLocation.tsx, frontend/src/components/Network.tsx, frontend/src/components/NetworkListTitle.tsx, frontend/src/index.tsx, frontend/src/models/networks.ts, scripts/notarize.js, scripts/sign.js
1. Sign in
2. Go to...
3. Click...
=> Fixing airbrake errors

frontend/package-lock.json, frontend/package.json, frontend/src/components/ConnectionDefaultsForm.tsx, frontend/src/components/DeviceContextWrapper.tsx, frontend/src/components/FilterDrawer.tsx, frontend/src/components/ServiceForm.tsx, frontend/src/helpers/connectionHelper.ts, frontend/src/models/connections.ts, frontend/src/models/devices.ts, frontend/src/models/networks.ts, frontend/src/models/search.ts, frontend/src/models/tags.ts, frontend/src/models/ui.ts, frontend/src/pages/DevicesPage/DevicesPage.tsx, frontend/src/pages/OrganizationRolePage.tsx, frontend/src/services/Notifications.ts, frontend/src/services/cloudController.ts
Seen errors in many old browsers in Airbrake.
=> Adding structuredClone pollyfil

backend/package-lock.json, backend/package.json, frontend/package-lock.json, frontend/package.json, frontend/src/components/AvatarMenu.tsx, frontend/src/components/OrganizationSelect.tsx, frontend/src/components/OrganizationSelectList.tsx, frontend/src/models/organization.ts, frontend/src/pages/NetworkPage.tsx, frontend/src/pages/OrganizationMembershipPage.tsx, frontend/src/selectors/organizations.ts, package-lock.json, package.json
Changing package name back to just remoteit
Avatar keyboard events fix
=> 3.16.0 alpha.9

backend/package-lock.json, backend/package.json, backend/src/ConnectionPool.ts, backend/src/cliStrings.ts, backend/src/sharedCopy/nameHelper.ts, frontend/package-lock.json, frontend/package.json, frontend/src/buttons/ComboButton/ComboButton.tsx, frontend/src/buttons/ConnectButton.tsx, frontend/src/components/AddDevice.tsx, frontend/src/components/Attributes.tsx, frontend/src/components/Avatar/Avatar.tsx, frontend/src/components/ConnectionData.tsx, frontend/src/components/ConnectionDetails.tsx, frontend/src/components/GuideBubble.tsx, frontend/src/components/OrganizationSelect.tsx, frontend/src/components/PlanActionChip.tsx, frontend/src/helpers/lanSharing.ts, frontend/src/pages/AddPage.tsx, frontend/src/pages/AddPlatformPage.tsx, frontend/src/pages/DeviceDetailPage/DeviceDetailPage.tsx, frontend/src/pages/DevicePage.tsx, frontend/src/pages/OrganizationPage.tsx, frontend/src/selectors/devices.ts, frontend/src/selectors/organizations.ts, frontend/src/selectors/state.ts, frontend/src/shared/nameHelper.ts, frontend/src/styling/theme.ts, package-lock.json, package.json
- UI improvements to highlight active organization
- Added org select guide bubble
- Display expired guide bubbles if in test mode
- Fixed LAN share host display when not binding to 0.0.0.0
- Removed duplicate info on device details page
- remoteit `v3.0.33`
- connectd `v4.17.0`
=> 3.17.1 Future

backend/package-lock.json, backend/package.json, backend/src/Connection.ts, frontend/package-lock.json, frontend/package.json, frontend/src/components/AddDevice.tsx, frontend/src/pages/AddPage.tsx, frontend/src/pages/AddPlatformPage.tsx, frontend/src/platforms/alpine/index.tsx, frontend/src/platforms/linux/index.tsx, frontend/src/platforms/openwrt/index.tsx, frontend/src/platforms/tinkerboard/index.tsx, frontend/src/platforms/ubuntu/index.tsx, frontend/src/services/Controller.ts, package-lock.json, package.json, src/ElectronApp.ts
- Moving org display on add device page 
- Change internal server from running on localhost to 127.0.0.1
- Don't filter out --enableCertificate argument from connection log
=> v3.17.2 Release

backend/package-lock.json, backend/package.json, backend/src/cli-version.json, backend/src/sudoPromise.ts, backend/src/types/sudo-prompt.d.ts, frontend/package-lock.json, frontend/package.json, frontend/src/buttons/CopyIconButton.tsx, frontend/src/components/AddDevice.tsx, frontend/src/components/AddDownload.tsx, frontend/src/components/CopyCodeBlock.tsx, frontend/src/components/ListItemLocation/ListItemLocation.tsx, frontend/src/components/NetworkListItem.tsx, frontend/src/components/NetworkListTitle.tsx, frontend/src/components/OrganizationIndicator.tsx, frontend/src/components/Plans.tsx, frontend/src/pages/AddPlatformPage.tsx, frontend/src/platforms/docker-jumpbox/index.tsx, frontend/src/selectors/connections.ts, package-lock.json, package.json
- Updating plans to show user/device/month limits
- Added native support for sudo-prompt for M2 macs
- Added copy code to add device pages
- Fixed avatar display on connections page
=> 3.18.0 alpha.2

backend/package-lock.json, backend/package.json, backend/src/sshConfig.ts, frontend/package-lock.json, frontend/package.json, frontend/src/buttons/CopyIconButton.tsx, frontend/src/buttons/LaunchButton/LaunchButton.tsx, frontend/src/components/Attributes.tsx, frontend/src/components/CustomConnectionSettings.tsx, frontend/src/components/DeleteAccountSection.tsx, frontend/src/components/DeviceConnectMenu.tsx, frontend/src/components/DeviceName.tsx, frontend/src/components/PlanCheckout.tsx, frontend/src/components/Plans.tsx, frontend/src/components/SeatsSetting.tsx, frontend/src/components/ServiceName/index.ts, frontend/src/helpers/connectionHelper.ts, frontend/src/pages/DevicePage.tsx, frontend/src/pages/OptionsPage.tsx, frontend/src/pages/UnauthorizedPage/UnauthorizedPage.tsx, frontend/src/services/Browser.ts, frontend/src/types.d.ts, package-lock.json, package.json
- Adding handling of null as a possible price interval
- Display when 'not remote configurable' instead of 'remote configurable'
- Fix Development env browser detection
- Add cost to reasons for delete request
- Update ssh config to auto generate .ssh/config and update tokens on copy/launch
=> v3.22.0 Release

backend/package-lock.json, backend/package.json, backend/src/sharedCopy/constants.ts, frontend/package-lock.json, frontend/package.json, frontend/public/index.html, frontend/src/buttons/ConnectButton.tsx, frontend/src/buttons/DynamicButton.tsx, frontend/src/components/Attributes.tsx, frontend/src/components/DeviceActionsBar.tsx, frontend/src/components/DeviceConnectMenu.tsx, frontend/src/components/DeviceList.tsx, frontend/src/components/DeviceListHeader.tsx, frontend/src/components/DeviceListItem.tsx, frontend/src/components/Header/Header.tsx, frontend/src/components/Link.tsx, frontend/src/components/ListHorizontal.tsx, frontend/src/components/Notice.tsx, frontend/src/components/PlanCard.tsx, frontend/src/components/RouteSetting.tsx, frontend/src/models/connections.ts, frontend/src/models/devices.ts, frontend/src/models/networks.ts, frontend/src/pages/AddPage.tsx, frontend/src/pages/AddPlatformPage.tsx, frontend/src/services/analytics.ts, frontend/src/shared/constants.ts, frontend/src/styling/theme.ts, package-lock.json, package.json
- Mobile screen size fixes
- Fixing bad GTM id in production build
- Provide a stop button to force stop connected connections
- Remove device fetching in progress check to keep it from locking out updates
=> v3.23.1 - Future

frontend/src/components/ConnectionDetails.tsx, frontend/src/components/DeviceList.tsx, frontend/src/components/RoleAccessCounts.tsx, frontend/src/components/Sidebar.tsx, frontend/src/hooks/useURLForm.ts, frontend/src/models/tags.ts, frontend/src/pages/OrganizationGuestPage.tsx, frontend/src/pages/OrganizationRolePage.tsx, frontend/src/shared/applications.ts
- Fixed excessive api calls when renaming a role
- Removed spaces in url config for new services
- Improved tag rename failure handling
- Help text updates
- Changed screen view launch protocol to https
=> Minor updates

.github/workflows/mobile-build.yml
1. Sign in
2. Go to...
3. Click...
=> Initial github workflow for mobile builds

backend/src/cliStrings.ts
=> [CLI-946] update the desktop commands for cli

android/app/build.gradle, backend/package-lock.json, backend/package.json, electron/package-lock.json, electron/package.json, frontend/package.json, frontend/src/buttons/RestoreButton.tsx, frontend/src/components/OnboardConfiguring.tsx, frontend/src/components/OnboardWifi.tsx, frontend/src/models/bluetooth.ts, frontend/src/pages/DevicesPage/DevicesPage.tsx, frontend/src/routers/OnboardRouter.tsx, frontend/src/routers/Router.tsx, ios/App/App.xcodeproj/project.pbxproj, package-lock.json, package.json
- Bluetooth onboarding processing fix
- Bluetooth restore device feature
=> v3.29.4-beta

backend/src/cliStrings.ts
=> [CLI-948] add flag to keep tools

frontend/src/components/DeviceContextWrapper.tsx, frontend/src/models/bluetooth.ts
=> updates for enhanced reconnect and finding device after registration

android/app/build.gradle, backend/package-lock.json, backend/package.json, electron/package-lock.json, electron/package.json, frontend/package.json, frontend/src/buttons/DynamicButton.tsx, frontend/src/buttons/RunButton.tsx, frontend/src/components/DevicesActionBar.tsx, frontend/src/components/FileAttributes.tsx, frontend/src/components/JobAttributes.tsx, frontend/src/components/MFA/MFAConfigureApp.tsx, frontend/src/components/MFA/MFAMethod.tsx, frontend/src/components/MFA/MFAPreference.tsx, frontend/src/components/ScriptForm.tsx, frontend/src/components/ScriptingHeader.tsx, frontend/src/components/TagAutocomplete.tsx, frontend/src/components/TagFilter.tsx, frontend/src/models/jobs.ts, frontend/src/pages/AddPage.tsx, frontend/src/pages/ScriptEditPage.tsx, frontend/src/pages/ScriptPage.tsx, frontend/src/platforms/idy/index.tsx, frontend/src/services/graphQLMutation.ts, ios/App/App.xcodeproj/project.pbxproj, package-lock.json, package.json, types.d.ts
- Added idy to "add device" page
- Fixed tag popover so that it always appears on screen
- Fixed updating, saving and running scripts
- Fixed two factor chip component display
=> v3.33.3-beta

.circleci/config.yml, ios/App/App.xcodeproj/project.pbxproj, ios/App/Podfile.lock
=> updating for expired cert
